In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By

In [3]:
driver=webdriver.Chrome()
driver.get('https://www.espn.com/soccer/stats/_/league/ENG.1/season/2022/view/scoring')

In [4]:
data=driver.find_element(By.XPATH,'//html/body/div[1]/div/div/div/div/main/div[2]/div[2]/div/div/section/div/section/div/div[1]/section/div/div[2]/div/div[2]/table/tbody').text
data

'1 Erling Haaland Manchester City 35 36\n2 Harry Kane Tottenham Hotspur 38 30\n3 Ivan Toney Brentford 33 20\n4 Mohamed Salah Liverpool 38 19\n5 Callum Wilson Newcastle United 31 18\n6 Marcus Rashford Manchester United 35 17\n7 Martin Ødegaard Arsenal 37 15\nOllie Watkins Aston Villa 37 15\nGabriel Martinelli Arsenal 36 15\n10 Bukayo Saka Arsenal 38 14\nAleksandar Mitrovic Fulham 24 14\n12 Harvey Barnes Leicester City 34 13\nRodrigo Leeds United 31 13\n14 Miguel Almirón Newcastle United 34 11\nPhil Foden Manchester City 32 11\nGabriel Jesus Arsenal 26 11\nRoberto Firmino Liverpool 25 11\n18 Eberechi Eze Crystal Palace 38 10\nSon Heung-Min Tottenham Hotspur 36 10\nAlexis Mac Allister Brighton & Hove Albion 35 10\nJames Maddison Leicester City 30 10\nTaiwo Awoniyi Nottingham Forest 27 10\nAlexander Isak Newcastle United 22 10\n24 James Ward-Prowse Southampton 38 9\nBryan Mbeumo Brentford 38 9\nPascal Groß Brighton & Hove Albion 37 9\nJulián Álvarez Manchester City 31 9\nDarwin Núñez Liverpool 29 9\n29 Brennan Johnson Nottingham Forest 38 8\nBruno Fernandes Manchester United 37 8\nLeandro Trossard Arsenal 36 8\nDanny Ings West Ham United 35 8\nIlkay Gündogan Manchester City 31 8\n34 Yoane Wissa Brentford 38 7\nGranit Xhaka Arsenal 37 7\nPhilip Billing AFC Bournemouth 36 7\nDwight McNeil Everton 36 7\nKai Havertz Chelsea 35 7\nSolly March Brighton & Hove Albion 33 7\nKaoru Mitoma Brighton & Hove Albion 33 7\nKevin De Bruyne Manchester City 32 7\nWilfried Zaha Crystal Palace 27 7\nDiogo Jota Liverpool 22 7\nCody Gakpo Liverpool 21 7\n45 Jarrod Bowen West Ham United 38 6\nDouglas Luiz Aston Villa 37 6\nRúben Neves Wolverhampton Wanderers 35 6\nJacob Ramsey Aston Villa 35 6\nSaïd Benrahma West Ham United 35 6\nDominic Solanke AFC Bournemouth 33 6'

In [5]:
data.split('\n')

['1 Erling Haaland Manchester City 35 36',
 '2 Harry Kane Tottenham Hotspur 38 30',
 '3 Ivan Toney Brentford 33 20',
 '4 Mohamed Salah Liverpool 38 19',
 '5 Callum Wilson Newcastle United 31 18',
 '6 Marcus Rashford Manchester United 35 17',
 '7 Martin Ødegaard Arsenal 37 15',
 'Ollie Watkins Aston Villa 37 15',
 'Gabriel Martinelli Arsenal 36 15',
 '10 Bukayo Saka Arsenal 38 14',
 'Aleksandar Mitrovic Fulham 24 14',
 '12 Harvey Barnes Leicester City 34 13',
 'Rodrigo Leeds United 31 13',
 '14 Miguel Almirón Newcastle United 34 11',
 'Phil Foden Manchester City 32 11',
 'Gabriel Jesus Arsenal 26 11',
 'Roberto Firmino Liverpool 25 11',
 '18 Eberechi Eze Crystal Palace 38 10',
 'Son Heung-Min Tottenham Hotspur 36 10',
 'Alexis Mac Allister Brighton & Hove Albion 35 10',
 'James Maddison Leicester City 30 10',
 'Taiwo Awoniyi Nottingham Forest 27 10',
 'Alexander Isak Newcastle United 22 10',
 '24 James Ward-Prowse Southampton 38 9',
 'Bryan Mbeumo Brentford 38 9',
 'Pascal Groß Brighton & Hove Albion 37 9',
 'Julián Álvarez Manchester City 31 9',
 'Darwin Núñez Liverpool 29 9',
 '29 Brennan Johnson Nottingham Forest 38 8',
 'Bruno Fernandes Manchester United 37 8',
 'Leandro Trossard Arsenal 36 8',
 'Danny Ings West Ham United 35 8',
 'Ilkay Gündogan Manchester City 31 8',
 '34 Yoane Wissa Brentford 38 7',
 'Granit Xhaka Arsenal 37 7',
 'Philip Billing AFC Bournemouth 36 7',
 'Dwight McNeil Everton 36 7',
 'Kai Havertz Chelsea 35 7',
 'Solly March Brighton & Hove Albion 33 7',
 'Kaoru Mitoma Brighton & Hove Albion 33 7',
 'Kevin De Bruyne Manchester City 32 7',
 'Wilfried Zaha Crystal Palace 27 7',
 'Diogo Jota Liverpool 22 7',
 'Cody Gakpo Liverpool 21 7',
 '45 Jarrod Bowen West Ham United 38 6',
 'Douglas Luiz Aston Villa 37 6',
 'Rúben Neves Wolverhampton Wanderers 35 6',
 'Jacob Ramsey Aston Villa 35 6',
 'Saïd Benrahma West Ham United 35 6',
 'Dominic Solanke AFC Bournemouth 33 6']

In [6]:
data.split('\n')[0]

'1 Erling Haaland Manchester City 35 36'

In [8]:
spli=data.split('\n')[0].split()
spli

['1', 'Erling', 'Haaland', 'Manchester', 'City', '35', '36']

In [8]:
data.split('\n')[0]

'1 Erling Haaland Manchester City 35 36'

In [9]:
spli.insert(0,'Top Scorers')

In [10]:
spli

['Top Scorers', '2', 'Harry', 'Kane', 'Tottenham', 'Hotspur', '38', '30']

In [11]:
spli.remove('Top Scorers')

In [12]:
spli

['2', 'Harry', 'Kane', 'Tottenham', 'Hotspur', '38', '30']

In [13]:
player=data.split('\n')[0:]

In [14]:
import numpy as np

In [15]:
player=np.array(player)

In [16]:
player

array(['1 Erling Haaland Manchester City 35 36',
       '2 Harry Kane Tottenham Hotspur 38 30',
       '3 Ivan Toney Brentford 33 20', '4 Mohamed Salah Liverpool 38 19',
       '5 Callum Wilson Newcastle United 31 18',
       '6 Marcus Rashford Manchester United 35 17',
       '7 Martin Ødegaard Arsenal 37 15',
       'Ollie Watkins Aston Villa 37 15',
       'Gabriel Martinelli Arsenal 36 15', '10 Bukayo Saka Arsenal 38 14',
       'Aleksandar Mitrovic Fulham 24 14',
       '12 Harvey Barnes Leicester City 34 13',
       'Rodrigo Leeds United 31 13',
       '14 Miguel Almirón Newcastle United 34 11',
       'Phil Foden Manchester City 32 11', 'Gabriel Jesus Arsenal 26 11',
       'Roberto Firmino Liverpool 25 11',
       '18 Eberechi Eze Crystal Palace 38 10',
       'Son Heung-Min Tottenham Hotspur 36 10',
       'Alexis Mac Allister Brighton & Hove Albion 35 10',
       'James Maddison Leicester City 30 10',
       'Taiwo Awoniyi Nottingham Forest 27 10',
       'Alexander Isak Newcastle United 22 10',
       '24 James Ward-Prowse Southampton 38 9',
       'Bryan Mbeumo Brentford 38 9',
       'Pascal Groß Brighton & Hove Albion 37 9',
       'Julián Álvarez Manchester City 31 9',
       'Darwin Núñez Liverpool 29 9',
       '29 Brennan Johnson Nottingham Forest 38 8',
       'Bruno Fernandes Manchester United 37 8',
       'Leandro Trossard Arsenal 36 8', 'Danny Ings West Ham United 35 8',
       'Ilkay Gündogan Manchester City 31 8',
       '34 Yoane Wissa Brentford 38 7', 'Granit Xhaka Arsenal 37 7',
       'Philip Billing AFC Bournemouth 36 7',
       'Dwight McNeil Everton 36 7', 'Kai Havertz Chelsea 35 7',
       'Solly March Brighton & Hove Albion 33 7',
       'Kaoru Mitoma Brighton & Hove Albion 33 7',
       'Kevin De Bruyne Manchester City 32 7',
       'Wilfried Zaha Crystal Palace 27 7', 'Diogo Jota Liverpool 22 7',
       'Cody Gakpo Liverpool 21 7',
       '45 Jarrod Bowen West Ham United 38 6',
       'Douglas Luiz Aston Villa 37 6',
       'Rúben Neves Wolverhampton Wanderers 35 6',
       'Jacob Ramsey Aston Villa 35 6',
       'Saïd Benrahma West Ham United 35 6',
       'Dominic Solanke AFC Bournemouth 33 6'], dtype='<U48')

In [17]:
import pandas as pd
df=pd.DataFrame(player)
df

C:\Users\Ryzen\AppData\Local\Temp\ipykernel_23264\3272937446.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

                                                   0
0             1 Erling Haaland Manchester City 35 36
1               2 Harry Kane Tottenham Hotspur 38 30
2                       3 Ivan Toney Brentford 33 20
3                    4 Mohamed Salah Liverpool 38 19
4             5 Callum Wilson Newcastle United 31 18
5          6 Marcus Rashford Manchester United 35 17
6                    7 Martin Ødegaard Arsenal 37 15
7                    Ollie Watkins Aston Villa 37 15
8                   Gabriel Martinelli Arsenal 36 15
9                       10 Bukayo Saka Arsenal 38 14
10                  Aleksandar Mitrovic Fulham 24 14
11             12 Harvey Barnes Leicester City 34 13
12                        Rodrigo Leeds United 31 13
13          14 Miguel Almirón Newcastle United 34 11
14                  Phil Foden Manchester City 32 11
15                       Gabriel Jesus Arsenal 26 11
16                   Roberto Firmino Liverpool 25 11
17              18 Eberechi Eze Crystal Palace 38 10
18             Son Heung-Min Tottenham Hotspur 36 10
19  Alexis Mac Allister Brighton & Hove Albion 35 10
20               James Maddison Leicester City 30 10
21             Taiwo Awoniyi Nottingham Forest 27 10
22             Alexander Isak Newcastle United 22 10
23             24 James Ward-Prowse Southampton 38 9
24                       Bryan Mbeumo Brentford 38 9
25           Pascal Groß Brighton & Hove Albion 37 9
26               Julián Álvarez Manchester City 31 9
27                       Darwin Núñez Liverpool 29 9
28         29 Brennan Johnson Nottingham Forest 38 8
29            Bruno Fernandes Manchester United 37 8
30                     Leandro Trossard Arsenal 36 8
31                   Danny Ings West Ham United 35 8
32               Ilkay Gündogan Manchester City 31 8
33                     34 Yoane Wissa Brentford 38 7
34                         Granit Xhaka Arsenal 37 7
35               Philip Billing AFC Bournemouth 36 7
36                        Dwight McNeil Everton 36 7
37                          Kai Havertz Chelsea 35 7
38           Solly March Brighton & Hove Albion 33 7
39          Kaoru Mitoma Brighton & Hove Albion 33 7
40              Kevin De Bruyne Manchester City 32 7
41                 Wilfried Zaha Crystal Palace 27 7
42                         Diogo Jota Liverpool 22 7
43                         Cody Gakpo Liverpool 21 7
44              45 Jarrod Bowen West Ham United 38 6
45                     Douglas Luiz Aston Villa 37 6
46          Rúben Neves Wolverhampton Wanderers 35 6
47                     Jacob Ramsey Aston Villa 35 6
48                Saïd Benrahma West Ham United 35 6
49              Dominic Solanke AFC Bournemouth 33 6

In [22]:
df=df[0].str.split(expand=True)

In [25]:
df['Name']=df[1].fillna('')+' '+df[2].fillna('')
df

,0,1,2,3,4,5,6,7,8,Name
0,1,Erling,Haaland,Manchester,City,35,36,None,None,Erling Haaland
1,2,Harry,Kane,Tottenham,Hotspur,38,30,None,None,Harry Kane
2,3,Ivan,Toney,Brentford,33,20,None,None,None,Ivan Toney
3,4,Mohamed,Salah,Liverpool,38,19,None,None,None,Mohamed Salah
4,5,Callum,Wilson,Newcastle,United,31,18,None,None,Callum Wilson
5,6,Marcus,Rashford,Manchester,United,35,17,None,None,Marcus Rashford
6,7,Martin,Ødegaard,Arsenal,37,15,None,None,None,Martin Ødegaard
7,Ollie,Watkins,Aston,Villa,37,15,None,None,None,Watkins Aston
8,Gabriel,Martinelli,Arsenal,36,15,None,None,None,None,Martinelli Arsenal
9,10,Bukayo,Saka,Arsenal,38,14,None,None,None,Bukayo Saka
10,Aleksandar,Mitrovic,Fulham,24,14,None,None,None,None,Mitrovic Fulham
11,12,Harvey,Barnes,Leicester,City,34,13,None,None,Harvey Barnes
12,Rodrigo,Leeds,United,31,13,None,None,None,None,Leeds United
13,14,Miguel,Almirón,Newcastle,United,34,11,None,None,Miguel Almirón
14,Phil,Foden,Manchester,City,32,11,None,None,None,Foden Manchester
15,Gabriel,Jesus,Arsenal,26,11,None,None,None,None,Jesus Arsenal
16,Roberto,Firmino,Liverpool,25,11,None,None,None,None,Firmino Liverpool
17,18,Eberechi,Eze,Crystal,Palace,38,10,None,None,Eberechi Eze
18,Son,Heung-Min,Tottenham,Hotspur,36,10,None,None,None,Heung-Min Tottenham
19,Alexis,Mac,Allister,Brighton,&,Hove,Albion,35,10,Mac Allister
20,James,Maddison,Leicester,City,30,10,None,None,None,Maddison Leicester
21,Taiwo,Awoniyi,Nottingham,Forest,27,10,None,None,None,Awoniyi Nottingham
22,Alexander,Isak,Newcastle,United,22,10,None,None,None,Isak Newcastle
23,24,James,Ward-Prowse,Southampton,38,9,None,None,None,James Ward-Prowse
24,Bryan,Mbeumo,Brentford,38,9,None,None,None,None,Mbeumo Brentford
25,Pascal,Groß,Brighton,&,Hove,Albion,37,9,None,Groß Brighton
26,Julián,Álvarez,Manchester,City,31,9,None,None,None,Álvarez Manchester
27,Darwin,Núñez,Liverpool,29,9,None,None,None,None,Núñez Liverpool
28,29,Brennan,Johnson,Nottingham,Forest,38,8,None,None,Brennan Johnson
29,Bruno,Fernandes,Manchester,United,37,8,None,None,None,Fernandes Manchester
30,Leandro,Trossard,Arsenal,36,8,None,None,None,None,Trossard Arsenal
31,Danny,Ings,West,Ham,United,35,8,None,None,Ings West
32,Ilkay,Gündogan,Manchester,City,31,8,None,None,None,Gündogan Manchester
33,34,Yoane,Wissa,Brentford,38,7,None,None,None,Yoane Wissa
34,Granit,Xhaka,Arsenal,37,7,None,None,None,None,Xhaka Arsenal
35,Philip,Billing,AFC,Bournemouth,36,7,None,None,None,Billing AFC
36,Dwight,McNeil,Everton,36,7,None,None,None,None,McNeil Everton
37,Kai,Havertz,Chelsea,35,7,None,None,None,None,Havertz Chelsea
38,Solly,March,Brighton,&,Hove,Albion,33,7,None,March Brighton
39,Kaoru,Mitoma,Brighton,&,Hove,Albion,33,7,None,Mitoma Brighton
40,Kevin,De,Bruyne,Manchester,City,32,7,None,None,De Bruyne
41,Wilfried,Zaha,Crystal,Palace,27,7,None,None,None,Zaha Crystal
42,Diogo,Jota,Liverpool,22,7,None,None,None,None,Jota Liverpool
43,Cody,Gakpo,Liverpool,21,7,None,None,None,None,Gakpo Liverpool
44,45,Jarrod,Bowen,West,Ham,United,38,6,None,Jarrod Bowen
45,Douglas,Luiz,Aston,Villa,37,6,None,None,None,Luiz Aston
46,Rúben,Neves,Wolverhampton,Wanderers,35,6,None,None,None,Neves Wolverhampton
47,Jacob,Ramsey,Aston,Villa,35,6,None,None,None,Ramsey Aston
48,Saïd,Benrahma,West,Ham,United,35,6,None,None,Benrahma West
49,Dominic,Solanke,AFC,Bournemouth,33,6,None,None,None,Solanke AFC

In [24]:
df.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 'Name'], dtype='object')