In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By

In [85]:
driver=webdriver.Chrome()
driver.get('https://www.iplt20.com/stats/2024')

In [86]:
data=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody').text

In [6]:
type(data)

str

In [7]:
len(data)

9274

In [12]:
data.split('\n')

['POS Player Runs Mat Inns NO HS Avg BF SR 100 50 4s 6s',
 '1',
 'Sai Sudharsan',
 'GT',
 '759 15 15 1 108* 54.21 486 156.17 1 6 88 21',
 '2',
 'Surya Kumar Yadav',
 'MI',
 '717 16 16 5 73* 65.18 427 167.91 0 5 69 38',
 '3',
 'Virat Kohli',
 'RCB',
 '657 15 15 3 73* 54.75 454 144.71 0 8 66 19',
 '4',
 'Shubman Gill',
 'GT',
 '650 15 15 2 93* 50.00 417 155.87 0 6 62 24',
 '5',
 'Mitchell Marsh',
 'LSG',
 '627 13 13 0 117 48.23 383 163.70 1 6 56 37',
 '6',
 'Shreyas Iyer',
 'PBKS',
 '604 17 17 5 97* 50.33 345 175.07 0 6 43 39',
 '7',
 'Yashasvi Jaiswal',
 'RR',
 '559 14 14 1 75 43.00 350 159.71 0 6 60 28',
 '8',
 'Prabhsimran Singh',
 'PBKS',
 '549 17 17 0 91 32.29 342 160.52 0 4 56 30',
 '9',
 'K L Rahul',
 'DC',
 '539 13 13 3 112* 53.90 360 149.72 1 3 52 21',
 '10',
 'Jos Buttler',
 'GT',
 '538 14 13 4 97* 59.78 330 163.03 0 5 52 24',
 '11',
 'Nicholas Pooran',
 'LSG',
 '524 14 14 2 87* 43.67 267 196.25 0 5 45 40',
 '12',
 'Heinrich Klaasen',
 'SRH',
 '487 13 13 2 105* 44.27 282 172.69 1 1 42 25',
 '13',
 'Priyansh Arya',
 'PBKS',
 '475 17 17 0 103 27.94 265 179.24 1 2 55 25',
 '14',
 'Aiden Markram',
 'LSG',
 '445 13 13 0 66 34.23 299 148.82 0 5 38 22',
 '15',
 'Abhishek Sharma',
 'SRH',
 '439 14 13 0 141 33.77 227 193.39 1 2 46 28',
 '16',
 'Rohit Sharma',
 'MI',
 '418 15 15 1 81 29.86 280 149.28 0 4 41 22',
 '17',
 'Phil Salt',
 'RCB',
 '403 13 13 1 65 33.58 229 175.98 0 4 48 22',
 '18',
 'Riyan Parag',
 'RR',
 '393 14 14 2 95 32.75 236 166.52 0 1 27 27',
 '19',
 'Ajinkya Rahane',
 'KKR',
 '390 13 12 1 61 35.45 264 147.72 0 3 36 20',
 '20',
 'Ryan Rickelton',
 'MI',
 '388 14 14 1 62* 29.85 257 150.97 0 3 47 17',
 '21',
 'Travis Head',
 'SRH',
 '374 13 12 0 76 31.17 230 162.60 0 3 50 15',
 '22',
 'Nehal Wadhera',
 'PBKS',
 '369 16 15 3 70 30.75 253 145.84 0 2 28 21',
 '23',
 'Shivam Dube',
 'CSK',
 '357 14 14 3 50 32.45 270 132.22 0 1 22 21',
 '24',
 'Ishan Kishan',
 'SRH',
 '354 14 13 3 106* 35.40 232 152.58 1 1 33 15',
 '25',
 'Shashank Singh',
 'PBKS',
 '350 17 14 7 61* 50.00 228 153.50 0 3 23 18',
 '26',
 'N Tilak Varma',
 'MI',
 '343 16 13 2 59 31.18 248 138.30 0 2 23 16',
 '27',
 'Dhruv Jurel',
 'RR',
 '333 14 13 4 70 37.00 213 156.33 0 2 22 22',
 '28',
 'Ayush Badoni',
 'LSG',
 '329 14 11 1 74 32.90 222 148.19 0 2 27 14',
 '29',
 'Rajat Patidar',
 'RCB',
 '312 15 14 1 64 24.00 217 143.77 0 2 25 14',
 '30',
 'Abishek Porel',
 'DC',
 '301 13 13 1 51 25.08 205 146.82 0 1 28 12',
 '31',
 'Ravindra Jadeja',
 'CSK',
 '301 14 14 5 77* 33.44 222 135.58 0 2 25 10',
 '32',
 'Tristan Stubbs',
 'DC',
 '300 14 13 7 41* 50.00 199 150.75 0 0 25 11',
 '33',
 'Angkrish Raghuvanshi',
 'KKR',
 '300 12 11 2 50 33.33 215 139.53 0 1 30 8',
 '34',
 'Sherfane Rutherford',
 'GT',
 '291 13 11 2 46 32.33 185 157.29 0 0 22 18',
 '35',
 'Sanju Samson',
 'RR',
 '285 9 9 1 66 35.63 203 140.39 0 1 27 13',
 '36',
 'Josh Inglis',
 'PBKS',
 '278 11 11 2 73 30.89 171 162.57 0 1 26 16',
 '37',
 'Rishabh Pant',
 'LSG',
 '269 14 13 2 118* 24.45 202 133.16 1 1 23 16',
 '38',
 'Axar Patel',
 'DC',
 '263 12 11 1 43 26.30 167 157.48 0 0 23 15',
 '39',
 'Jitesh Sharma',
 'RCB',
 '261 15 11 4 85* 37.29 148 176.35 0 1 24 17',
 '40',
 'Vaibhav Suryavanshi',
 'RR',
 '252 7 7 0 101 36.00 122 206.55 1 1 18 24',
 '41',
 'Naman Dhir',
 'MI',
 '252 16 12 4 46 31.50 138 182.60 0 0 24 13',
 '42',
 'Devdutt Padikkal',
 'RCB',
 '247 10 10 1 61 27.44 164 150.60 0 2 21 14',
 '43',
 'Sunil Narine',
 'KKR',
 '246 12 12 1 44 22.36 144 170.83 0 0 25 19',
 '44',
 'Ayush Mhatre',
 'CSK',
 '240 7 7 0 94 34.29 127 188.97 0 1 31 11',
 '45',
 'Shimron Hetmyer',
 'RR',
 '239 14 13 2 52 21.73 164 145.73 0 1 17 11',
 '46',
 'Aniket Verma',
 'SRH',
 '236 14 12 3 74 26.22 142 166.19 0 1 12 20',
 '47',
 'Will Jacks',
 'MI',
 '233 13 11 1 53 23.30 172 135.46 0 1 22 11',
 '48',
 'Dewald Brevis',
 'CSK',
 '225 6 6 0 57 37.50 125 180.00 0 2 13 17',
 '49',
 'Hardik Pandya',
 'MI',
 '224 15 12 3 48* 24.89 137 163.50 0 0 18 12',
 '50',
 'Nitish Rana',
 'RR',
 '217 11 11 1 81 21.70 134 161.94 0 2 27 9',
 '51',
 'Rinku Singh',
 'KKR',
 '206 13 11 4 38* 29.43 134 153.73 0 0 20 10',
 '52',
 'Ashutosh Sharma',
 'DC',
 '204 13 9 2 66* 29.14 127 160.62 0 1 14 13',
 '53',
 'Faf Du Plessis',
 'DC',
 '202 9 9 0 62 22.44 163 123.92 0 2 18 8',
 '54',
 'Karun Nair',
 'DC',
 '198 8 8 0 89 24.75 115 172.17 0 1 24 10',
 '55',
 'MS Dhoni',
 'CSK',
 '196 14 13 5 30* 24.50 145 135.17 0 0 12 12',
 '56',
 'Rachin Ravindra',
 'CSK',
 '191 8 8 1 65* 27.29 149 128.18 0 1 18 4',
 '57',
 'Tim David',
 'RCB',
 '187 12 9 6 50* 62.33 101 185.14 0 1 16 14',
 '58',
 'Nitish Kumar Reddy',
 'SRH',
 '182 13 11 3 32 22.75 153 118.95 0 0 16 4',
 '59',
 'Shahrukh Khan',
 'GT',
 '179 15 11 5 57 29.83 100 179.00 0 1 11 13',
 '60',
 'Andre Russell',
 'KKR',
 '167 13 10 1 57* 18.56 102 163.72 0 1 16 14',
 '61',
 'Abdul Samad',
 'LSG',
 '164 13 12 4 45 20.50 93 176.34 0 0 8 14',
 '62',
 'Marcus Stoinis',
 'PBKS',
 '160 13 11 5 44* 26.67 86 186.04 0 0 8 15',
 '63',
 'Devon Conway',
 'CSK',
 '156 6 6 0 69 26.00 119 131.09 0 2 17 4',
 '64',
 'David Miller',
 'LSG',
 '153 11 11 6 27* 30.60 120 127.50 0 0 13 4',
 '65',
 'Quinton De Kock',
 'KKR',
 '152 8 8 1 97* 21.71 117 129.91 0 1 9 11',
 '66',
 'Vipraj Nigam',
 'DC',
 '142 14 8 1 39 20.29 79 179.74 0 0 15 8',
 '67',
 'Venkatesh Iyer',
 'KKR',
 '142 11 7 0 60 20.29 102 139.21 0 1 15 4',
 '68',
 'Washington Sundar',
 'GT',
 '133 6 5 0 49 26.60 80 166.25 0 0 10 7',
 '69',
 'Ruturaj Gaikwad',
 'CSK',
 '122 5 5 0 63 24.40 81 150.61 0 2 14 4',
 '70',
 'Sameer Rizvi',
 'DC',
 '121 5 4 1 58* 40.33 79 153.16 0 1 11 7',
 '71',
 'Vijay Shankar',
 'CSK',
 '118 6 5 2 69* 39.33 91 129.67 0 1 8 3',
 '72',
 'Sam Curran',
 'CSK',
 '114 5 5 0 88 22.80 84 135.71 0 1 11 4',
 '73',
 'Liam Livingstone',
 'RCB',
 '112 10 8 1 54 16.00 84 133.33 0 1 4 9',
 '74',
 'Krunal Pandya',
 'RCB',
 '109 15 7 1 73* 18.17 86 126.74 0 1 9 4',
 '75',
 'Shubham Dubey',
 'RR',
 '106 9 8 4 34* 26.50 66 160.60 0 0 6 8',
 '76',
 'Rahul Tewatia',
 'GT',
 '99 15 12 4 24* 12.38 59 167.79 0 0 6 7',
 '77',
 'Pat Cummins',
 'SRH',
 '97 14 9 5 22* 24.25 58 167.24 0 0 6 7',
 '78',
 'Mayank Agarwal',
 'RCB',
 '95 4 4 1 41* 31.67 64 148.43 0 0 10 2',
 '79',
 'Manish Pandey',
 'KKR',
 '92 3 3 1 37 46.00 65 141.53 0 0 5 5',
 '80',
 'Kamindu Mendis',
 'SRH',
 '92 5 5 2 32* 30.67 69 133.33 0 0 7 2',
 '81',
 'Jonny Bairstow',
 'MI',
 '85 2 2 0 47 42.50 46 184.78 0 0 7 5',
 '82',
 'Marco Jansen',
 'PBKS',
 '75 14 8 4 34* 18.75 63 119.04 0 0 3 4',
 '83',
 'Rahmanullah Gurbaz',
 'KKR',
 '74 5 5 1 35 18.50 53 139.62 0 0 10 3',
 '84',
 'Shaik Rasheed',
 'CSK',
 '71 5 5 0 27 14.20 63 112.69 0 0 9 2',
 '85',
 'Romario Shepherd',
 'RCB',
 '70 8 3 1 53* 35.00 24 291.66 0 1 5 7',
 '86',
 'Urvil Patel',
 'CSK',
 '68 3 3 0 37 22.67 32 212.50 0 0 5 6',
 '87',
 'Jacob Bethell',
 'RCB',
 '67 2 2 0 55 33.50 39 171.79 0 1 9 3',
 '88',
 'Jofra Archer',
 'RR',
 '63 12 7 1 30 10.50 50 126.00 0 0 3 4',
 '89',
 'Abhinav Manohar',
 'SRH',
 '61 8 5 0 43 12.20 61 100.00 0 0 2 4',
 '90',
 'Azmatullah Omarzai',
 'PBKS',
 '57 9 5 1 21* 14.25 41 139.02 0 0 6 3',
 '91',
 'Harshit Rana',
 'KKR',
 '57 13 7 3 34 14.25 53 107.54 0 0 5 3',
 '92',
 'Jake Fraser - McGurk',
 'DC',
 '55 6 6 0 38 9.17 52 105.76 0 0 7 2',
 '93',
 'Rahul Tripathi',
 'CSK',
 '55 5 5 0 23 11.00 57 96.49 0 0 6 1',
 '94',
 'Glenn Maxwell',
 'PBKS',
 '48 7 6 0 30 8.00 49 97.95 0 0 5 1',
 '95',
 'Corbin Bosch',
 'MI',
 '47 2 2 0 27 23.50 32 146.87 0 0 3 3',
 '96',
 'Ramandeep Singh',
 'KKR',
 '47 11 7 2 22 9.40 35 134.28 0 0 1 4',
 '97',
 'Rashid Khan',
 'GT',
 '40 15 8 3 12 8.00 28 142.85 0 0 2 3',
 '98',
 'Mitchell Santner',
 'MI',
 '40 13 8 6 18* 20.00 33 121.21 0 0 2 3',
 '99',
 'Deepak Chahar',
 'MI',
 '37 14 4 3 28* 37.00 25 148.00 0 0 3 2',
 '100',
 'Ravichandran Ashwin',
 'CSK',
 '33 9 4 0 13 8.25 30 110.00 0 0 3 1',
 '101',
 'Deepak Hooda',
 'CSK',
 '31 7 5 0 22 6.20 41 75.60 0 0 2 1',
 '102',
 'Mohd Arshad Khan',
 'GT',
 '23 9 5 3 20 11.50 19 121.05 0 0 0 3',
 '103',
 'Sediqullah Atal',
 'DC',
 '22 1 1 0 22 22.00 16 137.50 0 0 0 2',
 '104',
 'Avesh Khan',
 'LSG',
 '21 13 4 3 19* 21.00 12 175.00 0 0 3 1',
 '105',
 'Harshal Patel',
 'SRH',
 '21 13 4 2 12* 10.50 26 80.76 0 0 0 0',
 '106',
 'Kusal Mendis',
 'GT',
 '20 1 1 0 20 20.00 10 200.00 0 0 1 2',
 '107',
 'Shardul Thakur',
 'LSG',
 '18 10 5 2 6 6.00 12 150.00 0 0 3 0',
 '108',
 'Kuldeep Yadav',
 'DC',
 '18 14 5 2 7 6.00 16 112.50 0 0 2 0',
 '109',
 'Gerald Coetzee',
 'GT',
 '17 4 2 0 12 8.50 11 154.54 0 0 2 1',
 '110',
 'Jamie Overton',
 'CSK',
 '15 3 2 2 11* - 7 214.28 0 0 1 1',
 '111',
 'Anshul Kamboj',
 'CSK',
 '14 8 5 3 5* 7.00 12 116.66 0 0 2 0',
 '112',
 'Matthew Breetzke',
 'LSG',
 '14 1 1 0 14 14.00 12 116.66 0 0 1 1',
 '113',
 'Bhuvneshwar Kumar',
 'RCB',
 '14 14 6 3 8 4.67 25 56.00 0 0 1 0',
 '114',
 'Atharva Taide',
 'SRH',
 '13 1 1 0 13 13.00 9 144.44 0 0 3 0',
 '115',
 'Ravi Bishnoi',
 'LSG',
 '13 11 3 1 13 6.50 16 81.25 0 0 0 2',
 '116',
 'Harpreet Brar',
 'PBKS',
 '11 8 2 1 7* 11.00 13 84.61 0 0 0 1',
 '117',
 'Xavier Bartlett',
 'PBKS',
 '11 4 1 0 11 11.00 15 73.33 0 0 1 0',
 '118',
 'Mohammad Shami',
 'SRH',
 '10 9 4 3 6* 10.00 10 100.00 0 0 1 0',
 '119',
 'Dushmantha Chameera',
 'DC',
 '10 6 3 3 8* - 14 71.42 0 0 0 0',
 '120',
 'Maheesh Theekshana',
 'RR',
 '10 11 4 2 5 5.00 27 37.03 0 0 0 0',
 '121',
 'Kagiso Rabada',
 'GT',
 '9 4 2 1 7* 9.00 8 112.50 0 0 0 1',
 '122',
 'Shahbaz Ahmed',
 'LSG',
 '9 3 1 0 9 9.00 8 112.50 0 0 1 0',
 '123',
 'Wiaan Mulder',
 'SRH',
 '9 1 1 0 9 9.00 11 81.81 0 0 1 0',
 '124',
 'Wanindu Hasaranga',
 'RR',
 '9 11 5 0 4 1.80 15 60.00 0 0 0 0',
 '125',
 'Kwena Maphaka',
 'RR',
 '8 2 1 1 8* - 2 400.00 0 0 2 0',
 '126',
 'Raj Angad Bawa',
 'MI',
 '8 3 1 1 8* - 4 200.00 0 0 0 0',
 '127',
 'Tushar Deshpande',
 'RR',
 '7 10 4 3 3 7.00 8 87.50 0 0 0 0',
 '128',
 'Suryansh Shedge',
 'PBKS',
 '7 5 3 0 4 2.33 11 63.63 0 0 0 0',
 '129',
 'Noor Ahmad',
 'CSK',
 '7 14 6 2 2* 1.75 17 41.17 0 0 0 0',
 '130',
 'Akash Deep',
 'LSG',
 '6 6 2 1 6* 6.00 2 300.00 0 0 0 1',
 '131',
 'Sandeep Sharma',
 'RR',
 '6 10 1 1 6* - 5 120.00 0 0 0 0',
 '132',
 'Mitchell Starc',
 'DC',
 '6 11 6 4 2* 3.00 10 60.00 0 0 0 0',
 '133',
 'Robin Minz',
 'MI',
 '6 2 2 0 3 3.00 15 40.00 0 0 0 0',
 '134',
 'Rovman Powell',
 'KKR',
 '5 2 1 0 5 5.00 5 100.00 0 0 1 0',
 '135',
 'Sai Kishore',
 'GT',
 '5 15 3 0 3 1.67 10 50.00 0 0 0 0',
 '136',
 'Prince Yadav',
 'LSG',
 '5 6 2 2 4* - 10 50.00 0 0 0 0',
 '137',
 'Moeen Ali',
 'KKR',
 '5 6 2 0 5 2.50 14 35.71 0 0 0 0',
 '138',
 'Lockie Ferguson',
 'PBKS',
 '4 4 1 1 4* - 1 400.00 0 0 1 0',
 '139',
 'Yash Dayal',
 'RCB',
 '4 15 3 1 3 2.00 8 50.00 0 0 0 0',
 '140',
 'Akash Madhwal',
 'RR',
 '4 4 1 1 4* - 9 44.44 0 0 0 0',
 '141',
 'Madhav Tiwari',
 'DC',
 '3 1 1 0 3 3.00 4 75.00 0 0 0 0',
 '142',
 'Mohammed Siraj',
 'GT',
 '3 15 1 1 3* - 4 75.00 0 0 0 0',
 '143',
 'Kumar Kartikeya Singh',
 'RR',
 '3 4 2 0 2 1.50 5 60.00 0 0 0 0',
 '144',
 'Simarjeet Singh',
 'SRH',
 '3 4 3 1 3* 1.50 7 42.85 0 0 0 0',
 '145',
 'Fazalhaq Farooqi',
 'RR',
 '2 5 1 1 2* - 2 100.00 0 0 0 0',
 '146',
 'Trent Boult',
 'MI',
 '2 16 2 1 1* 2.00 3 66.66 0 0 0 0',
 '147',
 'Spencer Johnson',
 'KKR',
 '2 4 2 2 1* - 4 50.00 0 0 0 0',
 '148',
 'Arshdeep Singh',
 'PBKS',
 '2 17 2 1 1* 2.00 6 33.33 0 0 0 0',
 '149',
 'Varun Chakaravarthy',
 'KKR',
 '1 13 1 1 1* - 1 100.00 0 0 0 0',
 '150',
 'V Satyanarayana Penmetsa',
 'MI',
 '1 2 1 1 1* - 1 100.00 0 0 0 0',
 '151',
 'Karn Sharma',
 'MI',
 '1 6 1 1 1* - 1 100.00 0 0 0 0',
 '152',
 'Khaleel Ahmed',
 'CSK',
 '1 14 2 2 1* - 2 50.00 0 0 0 0',
 '153',
 'Mohit Sharma',
 'DC',
 '1 8 2 1 1* 1.00 3 33.33 0 0 0 0',
 '154',
 'Donovan Ferreira',
 'DC',
 '1 1 1 0 1 1.00 3 33.33 0 0 0 0',
 '155',
 'Digvesh Singh',
 'LSG',
 '1 13 2 1 1 1.00 3 33.33 0 0 0 0',
 '156',
 'Manoj Bhandage',
 'RCB',
 '1 1 1 0 1 1.00 4 25.00 0 0 0 0']

In [16]:
data.split('\n')[0]

'POS Player Runs Mat Inns NO HS Avg BF SR 100 50 4s 6s'

In [73]:
cols=data.split('\n')[0].split()

In [74]:
cols

['POS',
 'Player',
 'Runs',
 'Mat',
 'Inns',
 'NO',
 'HS',
 'Avg',
 'BF',
 'SR',
 '100',
 '50',
 '4s',
 '6s']

In [28]:
player=data.split('\n')[1:]
player

['1',
 'Sai Sudharsan',
 'GT',
 '759 15 15 1 108* 54.21 486 156.17 1 6 88 21',
 '2',
 'Surya Kumar Yadav',
 'MI',
 '717 16 16 5 73* 65.18 427 167.91 0 5 69 38',
 '3',
 'Virat Kohli',
 'RCB',
 '657 15 15 3 73* 54.75 454 144.71 0 8 66 19',
 '4',
 'Shubman Gill',
 'GT',
 '650 15 15 2 93* 50.00 417 155.87 0 6 62 24',
 '5',
 'Mitchell Marsh',
 'LSG',
 '627 13 13 0 117 48.23 383 163.70 1 6 56 37',
 '6',
 'Shreyas Iyer',
 'PBKS',
 '604 17 17 5 97* 50.33 345 175.07 0 6 43 39',
 '7',
 'Yashasvi Jaiswal',
 'RR',
 '559 14 14 1 75 43.00 350 159.71 0 6 60 28',
 '8',
 'Prabhsimran Singh',
 'PBKS',
 '549 17 17 0 91 32.29 342 160.52 0 4 56 30',
 '9',
 'K L Rahul',
 'DC',
 '539 13 13 3 112* 53.90 360 149.72 1 3 52 21',
 '10',
 'Jos Buttler',
 'GT',
 '538 14 13 4 97* 59.78 330 163.03 0 5 52 24',
 '11',
 'Nicholas Pooran',
 'LSG',
 '524 14 14 2 87* 43.67 267 196.25 0 5 45 40',
 '12',
 'Heinrich Klaasen',
 'SRH',
 '487 13 13 2 105* 44.27 282 172.69 1 1 42 25',
 '13',
 'Priyansh Arya',
 'PBKS',
 '475 17 17 0 103 27.94 265 179.24 1 2 55 25',
 '14',
 'Aiden Markram',
 'LSG',
 '445 13 13 0 66 34.23 299 148.82 0 5 38 22',
 '15',
 'Abhishek Sharma',
 'SRH',
 '439 14 13 0 141 33.77 227 193.39 1 2 46 28',
 '16',
 'Rohit Sharma',
 'MI',
 '418 15 15 1 81 29.86 280 149.28 0 4 41 22',
 '17',
 'Phil Salt',
 'RCB',
 '403 13 13 1 65 33.58 229 175.98 0 4 48 22',
 '18',
 'Riyan Parag',
 'RR',
 '393 14 14 2 95 32.75 236 166.52 0 1 27 27',
 '19',
 'Ajinkya Rahane',
 'KKR',
 '390 13 12 1 61 35.45 264 147.72 0 3 36 20',
 '20',
 'Ryan Rickelton',
 'MI',
 '388 14 14 1 62* 29.85 257 150.97 0 3 47 17',
 '21',
 'Travis Head',
 'SRH',
 '374 13 12 0 76 31.17 230 162.60 0 3 50 15',
 '22',
 'Nehal Wadhera',
 'PBKS',
 '369 16 15 3 70 30.75 253 145.84 0 2 28 21',
 '23',
 'Shivam Dube',
 'CSK',
 '357 14 14 3 50 32.45 270 132.22 0 1 22 21',
 '24',
 'Ishan Kishan',
 'SRH',
 '354 14 13 3 106* 35.40 232 152.58 1 1 33 15',
 '25',
 'Shashank Singh',
 'PBKS',
 '350 17 14 7 61* 50.00 228 153.50 0 3 23 18',
 '26',
 'N Tilak Varma',
 'MI',
 '343 16 13 2 59 31.18 248 138.30 0 2 23 16',
 '27',
 'Dhruv Jurel',
 'RR',
 '333 14 13 4 70 37.00 213 156.33 0 2 22 22',
 '28',
 'Ayush Badoni',
 'LSG',
 '329 14 11 1 74 32.90 222 148.19 0 2 27 14',
 '29',
 'Rajat Patidar',
 'RCB',
 '312 15 14 1 64 24.00 217 143.77 0 2 25 14',
 '30',
 'Abishek Porel',
 'DC',
 '301 13 13 1 51 25.08 205 146.82 0 1 28 12',
 '31',
 'Ravindra Jadeja',
 'CSK',
 '301 14 14 5 77* 33.44 222 135.58 0 2 25 10',
 '32',
 'Tristan Stubbs',
 'DC',
 '300 14 13 7 41* 50.00 199 150.75 0 0 25 11',
 '33',
 'Angkrish Raghuvanshi',
 'KKR',
 '300 12 11 2 50 33.33 215 139.53 0 1 30 8',
 '34',
 'Sherfane Rutherford',
 'GT',
 '291 13 11 2 46 32.33 185 157.29 0 0 22 18',
 '35',
 'Sanju Samson',
 'RR',
 '285 9 9 1 66 35.63 203 140.39 0 1 27 13',
 '36',
 'Josh Inglis',
 'PBKS',
 '278 11 11 2 73 30.89 171 162.57 0 1 26 16',
 '37',
 'Rishabh Pant',
 'LSG',
 '269 14 13 2 118* 24.45 202 133.16 1 1 23 16',
 '38',
 'Axar Patel',
 'DC',
 '263 12 11 1 43 26.30 167 157.48 0 0 23 15',
 '39',
 'Jitesh Sharma',
 'RCB',
 '261 15 11 4 85* 37.29 148 176.35 0 1 24 17',
 '40',
 'Vaibhav Suryavanshi',
 'RR',
 '252 7 7 0 101 36.00 122 206.55 1 1 18 24',
 '41',
 'Naman Dhir',
 'MI',
 '252 16 12 4 46 31.50 138 182.60 0 0 24 13',
 '42',
 'Devdutt Padikkal',
 'RCB',
 '247 10 10 1 61 27.44 164 150.60 0 2 21 14',
 '43',
 'Sunil Narine',
 'KKR',
 '246 12 12 1 44 22.36 144 170.83 0 0 25 19',
 '44',
 'Ayush Mhatre',
 'CSK',
 '240 7 7 0 94 34.29 127 188.97 0 1 31 11',
 '45',
 'Shimron Hetmyer',
 'RR',
 '239 14 13 2 52 21.73 164 145.73 0 1 17 11',
 '46',
 'Aniket Verma',
 'SRH',
 '236 14 12 3 74 26.22 142 166.19 0 1 12 20',
 '47',
 'Will Jacks',
 'MI',
 '233 13 11 1 53 23.30 172 135.46 0 1 22 11',
 '48',
 'Dewald Brevis',
 'CSK',
 '225 6 6 0 57 37.50 125 180.00 0 2 13 17',
 '49',
 'Hardik Pandya',
 'MI',
 '224 15 12 3 48* 24.89 137 163.50 0 0 18 12',
 '50',
 'Nitish Rana',
 'RR',
 '217 11 11 1 81 21.70 134 161.94 0 2 27 9',
 '51',
 'Rinku Singh',
 'KKR',
 '206 13 11 4 38* 29.43 134 153.73 0 0 20 10',
 '52',
 'Ashutosh Sharma',
 'DC',
 '204 13 9 2 66* 29.14 127 160.62 0 1 14 13',
 '53',
 'Faf Du Plessis',
 'DC',
 '202 9 9 0 62 22.44 163 123.92 0 2 18 8',
 '54',
 'Karun Nair',
 'DC',
 '198 8 8 0 89 24.75 115 172.17 0 1 24 10',
 '55',
 'MS Dhoni',
 'CSK',
 '196 14 13 5 30* 24.50 145 135.17 0 0 12 12',
 '56',
 'Rachin Ravindra',
 'CSK',
 '191 8 8 1 65* 27.29 149 128.18 0 1 18 4',
 '57',
 'Tim David',
 'RCB',
 '187 12 9 6 50* 62.33 101 185.14 0 1 16 14',
 '58',
 'Nitish Kumar Reddy',
 'SRH',
 '182 13 11 3 32 22.75 153 118.95 0 0 16 4',
 '59',
 'Shahrukh Khan',
 'GT',
 '179 15 11 5 57 29.83 100 179.00 0 1 11 13',
 '60',
 'Andre Russell',
 'KKR',
 '167 13 10 1 57* 18.56 102 163.72 0 1 16 14',
 '61',
 'Abdul Samad',
 'LSG',
 '164 13 12 4 45 20.50 93 176.34 0 0 8 14',
 '62',
 'Marcus Stoinis',
 'PBKS',
 '160 13 11 5 44* 26.67 86 186.04 0 0 8 15',
 '63',
 'Devon Conway',
 'CSK',
 '156 6 6 0 69 26.00 119 131.09 0 2 17 4',
 '64',
 'David Miller',
 'LSG',
 '153 11 11 6 27* 30.60 120 127.50 0 0 13 4',
 '65',
 'Quinton De Kock',
 'KKR',
 '152 8 8 1 97* 21.71 117 129.91 0 1 9 11',
 '66',
 'Vipraj Nigam',
 'DC',
 '142 14 8 1 39 20.29 79 179.74 0 0 15 8',
 '67',
 'Venkatesh Iyer',
 'KKR',
 '142 11 7 0 60 20.29 102 139.21 0 1 15 4',
 '68',
 'Washington Sundar',
 'GT',
 '133 6 5 0 49 26.60 80 166.25 0 0 10 7',
 '69',
 'Ruturaj Gaikwad',
 'CSK',
 '122 5 5 0 63 24.40 81 150.61 0 2 14 4',
 '70',
 'Sameer Rizvi',
 'DC',
 '121 5 4 1 58* 40.33 79 153.16 0 1 11 7',
 '71',
 'Vijay Shankar',
 'CSK',
 '118 6 5 2 69* 39.33 91 129.67 0 1 8 3',
 '72',
 'Sam Curran',
 'CSK',
 '114 5 5 0 88 22.80 84 135.71 0 1 11 4',
 '73',
 'Liam Livingstone',
 'RCB',
 '112 10 8 1 54 16.00 84 133.33 0 1 4 9',
 '74',
 'Krunal Pandya',
 'RCB',
 '109 15 7 1 73* 18.17 86 126.74 0 1 9 4',
 '75',
 'Shubham Dubey',
 'RR',
 '106 9 8 4 34* 26.50 66 160.60 0 0 6 8',
 '76',
 'Rahul Tewatia',
 'GT',
 '99 15 12 4 24* 12.38 59 167.79 0 0 6 7',
 '77',
 'Pat Cummins',
 'SRH',
 '97 14 9 5 22* 24.25 58 167.24 0 0 6 7',
 '78',
 'Mayank Agarwal',
 'RCB',
 '95 4 4 1 41* 31.67 64 148.43 0 0 10 2',
 '79',
 'Manish Pandey',
 'KKR',
 '92 3 3 1 37 46.00 65 141.53 0 0 5 5',
 '80',
 'Kamindu Mendis',
 'SRH',
 '92 5 5 2 32* 30.67 69 133.33 0 0 7 2',
 '81',
 'Jonny Bairstow',
 'MI',
 '85 2 2 0 47 42.50 46 184.78 0 0 7 5',
 '82',
 'Marco Jansen',
 'PBKS',
 '75 14 8 4 34* 18.75 63 119.04 0 0 3 4',
 '83',
 'Rahmanullah Gurbaz',
 'KKR',
 '74 5 5 1 35 18.50 53 139.62 0 0 10 3',
 '84',
 'Shaik Rasheed',
 'CSK',
 '71 5 5 0 27 14.20 63 112.69 0 0 9 2',
 '85',
 'Romario Shepherd',
 'RCB',
 '70 8 3 1 53* 35.00 24 291.66 0 1 5 7',
 '86',
 'Urvil Patel',
 'CSK',
 '68 3 3 0 37 22.67 32 212.50 0 0 5 6',
 '87',
 'Jacob Bethell',
 'RCB',
 '67 2 2 0 55 33.50 39 171.79 0 1 9 3',
 '88',
 'Jofra Archer',
 'RR',
 '63 12 7 1 30 10.50 50 126.00 0 0 3 4',
 '89',
 'Abhinav Manohar',
 'SRH',
 '61 8 5 0 43 12.20 61 100.00 0 0 2 4',
 '90',
 'Azmatullah Omarzai',
 'PBKS',
 '57 9 5 1 21* 14.25 41 139.02 0 0 6 3',
 '91',
 'Harshit Rana',
 'KKR',
 '57 13 7 3 34 14.25 53 107.54 0 0 5 3',
 '92',
 'Jake Fraser - McGurk',
 'DC',
 '55 6 6 0 38 9.17 52 105.76 0 0 7 2',
 '93',
 'Rahul Tripathi',
 'CSK',
 '55 5 5 0 23 11.00 57 96.49 0 0 6 1',
 '94',
 'Glenn Maxwell',
 'PBKS',
 '48 7 6 0 30 8.00 49 97.95 0 0 5 1',
 '95',
 'Corbin Bosch',
 'MI',
 '47 2 2 0 27 23.50 32 146.87 0 0 3 3',
 '96',
 'Ramandeep Singh',
 'KKR',
 '47 11 7 2 22 9.40 35 134.28 0 0 1 4',
 '97',
 'Rashid Khan',
 'GT',
 '40 15 8 3 12 8.00 28 142.85 0 0 2 3',
 '98',
 'Mitchell Santner',
 'MI',
 '40 13 8 6 18* 20.00 33 121.21 0 0 2 3',
 '99',
 'Deepak Chahar',
 'MI',
 '37 14 4 3 28* 37.00 25 148.00 0 0 3 2',
 '100',
 'Ravichandran Ashwin',
 'CSK',
 '33 9 4 0 13 8.25 30 110.00 0 0 3 1',
 '101',
 'Deepak Hooda',
 'CSK',
 '31 7 5 0 22 6.20 41 75.60 0 0 2 1',
 '102',
 'Mohd Arshad Khan',
 'GT',
 '23 9 5 3 20 11.50 19 121.05 0 0 0 3',
 '103',
 'Sediqullah Atal',
 'DC',
 '22 1 1 0 22 22.00 16 137.50 0 0 0 2',
 '104',
 'Avesh Khan',
 'LSG',
 '21 13 4 3 19* 21.00 12 175.00 0 0 3 1',
 '105',
 'Harshal Patel',
 'SRH',
 '21 13 4 2 12* 10.50 26 80.76 0 0 0 0',
 '106',
 'Kusal Mendis',
 'GT',
 '20 1 1 0 20 20.00 10 200.00 0 0 1 2',
 '107',
 'Shardul Thakur',
 'LSG',
 '18 10 5 2 6 6.00 12 150.00 0 0 3 0',
 '108',
 'Kuldeep Yadav',
 'DC',
 '18 14 5 2 7 6.00 16 112.50 0 0 2 0',
 '109',
 'Gerald Coetzee',
 'GT',
 '17 4 2 0 12 8.50 11 154.54 0 0 2 1',
 '110',
 'Jamie Overton',
 'CSK',
 '15 3 2 2 11* - 7 214.28 0 0 1 1',
 '111',
 'Anshul Kamboj',
 'CSK',
 '14 8 5 3 5* 7.00 12 116.66 0 0 2 0',
 '112',
 'Matthew Breetzke',
 'LSG',
 '14 1 1 0 14 14.00 12 116.66 0 0 1 1',
 '113',
 'Bhuvneshwar Kumar',
 'RCB',
 '14 14 6 3 8 4.67 25 56.00 0 0 1 0',
 '114',
 'Atharva Taide',
 'SRH',
 '13 1 1 0 13 13.00 9 144.44 0 0 3 0',
 '115',
 'Ravi Bishnoi',
 'LSG',
 '13 11 3 1 13 6.50 16 81.25 0 0 0 2',
 '116',
 'Harpreet Brar',
 'PBKS',
 '11 8 2 1 7* 11.00 13 84.61 0 0 0 1',
 '117',
 'Xavier Bartlett',
 'PBKS',
 '11 4 1 0 11 11.00 15 73.33 0 0 1 0',
 '118',
 'Mohammad Shami',
 'SRH',
 '10 9 4 3 6* 10.00 10 100.00 0 0 1 0',
 '119',
 'Dushmantha Chameera',
 'DC',
 '10 6 3 3 8* - 14 71.42 0 0 0 0',
 '120',
 'Maheesh Theekshana',
 'RR',
 '10 11 4 2 5 5.00 27 37.03 0 0 0 0',
 '121',
 'Kagiso Rabada',
 'GT',
 '9 4 2 1 7* 9.00 8 112.50 0 0 0 1',
 '122',
 'Shahbaz Ahmed',
 'LSG',
 '9 3 1 0 9 9.00 8 112.50 0 0 1 0',
 '123',
 'Wiaan Mulder',
 'SRH',
 '9 1 1 0 9 9.00 11 81.81 0 0 1 0',
 '124',
 'Wanindu Hasaranga',
 'RR',
 '9 11 5 0 4 1.80 15 60.00 0 0 0 0',
 '125',
 'Kwena Maphaka',
 'RR',
 '8 2 1 1 8* - 2 400.00 0 0 2 0',
 '126',
 'Raj Angad Bawa',
 'MI',
 '8 3 1 1 8* - 4 200.00 0 0 0 0',
 '127',
 'Tushar Deshpande',
 'RR',
 '7 10 4 3 3 7.00 8 87.50 0 0 0 0',
 '128',
 'Suryansh Shedge',
 'PBKS',
 '7 5 3 0 4 2.33 11 63.63 0 0 0 0',
 '129',
 'Noor Ahmad',
 'CSK',
 '7 14 6 2 2* 1.75 17 41.17 0 0 0 0',
 '130',
 'Akash Deep',
 'LSG',
 '6 6 2 1 6* 6.00 2 300.00 0 0 0 1',
 '131',
 'Sandeep Sharma',
 'RR',
 '6 10 1 1 6* - 5 120.00 0 0 0 0',
 '132',
 'Mitchell Starc',
 'DC',
 '6 11 6 4 2* 3.00 10 60.00 0 0 0 0',
 '133',
 'Robin Minz',
 'MI',
 '6 2 2 0 3 3.00 15 40.00 0 0 0 0',
 '134',
 'Rovman Powell',
 'KKR',
 '5 2 1 0 5 5.00 5 100.00 0 0 1 0',
 '135',
 'Sai Kishore',
 'GT',
 '5 15 3 0 3 1.67 10 50.00 0 0 0 0',
 '136',
 'Prince Yadav',
 'LSG',
 '5 6 2 2 4* - 10 50.00 0 0 0 0',
 '137',
 'Moeen Ali',
 'KKR',
 '5 6 2 0 5 2.50 14 35.71 0 0 0 0',
 '138',
 'Lockie Ferguson',
 'PBKS',
 '4 4 1 1 4* - 1 400.00 0 0 1 0',
 '139',
 'Yash Dayal',
 'RCB',
 '4 15 3 1 3 2.00 8 50.00 0 0 0 0',
 '140',
 'Akash Madhwal',
 'RR',
 '4 4 1 1 4* - 9 44.44 0 0 0 0',
 '141',
 'Madhav Tiwari',
 'DC',
 '3 1 1 0 3 3.00 4 75.00 0 0 0 0',
 '142',
 'Mohammed Siraj',
 'GT',
 '3 15 1 1 3* - 4 75.00 0 0 0 0',
 '143',
 'Kumar Kartikeya Singh',
 'RR',
 '3 4 2 0 2 1.50 5 60.00 0 0 0 0',
 '144',
 'Simarjeet Singh',
 'SRH',
 '3 4 3 1 3* 1.50 7 42.85 0 0 0 0',
 '145',
 'Fazalhaq Farooqi',
 'RR',
 '2 5 1 1 2* - 2 100.00 0 0 0 0',
 '146',
 'Trent Boult',
 'MI',
 '2 16 2 1 1* 2.00 3 66.66 0 0 0 0',
 '147',
 'Spencer Johnson',
 'KKR',
 '2 4 2 2 1* - 4 50.00 0 0 0 0',
 '148',
 'Arshdeep Singh',
 'PBKS',
 '2 17 2 1 1* 2.00 6 33.33 0 0 0 0',
 '149',
 'Varun Chakaravarthy',
 'KKR',
 '1 13 1 1 1* - 1 100.00 0 0 0 0',
 '150',
 'V Satyanarayana Penmetsa',
 'MI',
 '1 2 1 1 1* - 1 100.00 0 0 0 0',
 '151',
 'Karn Sharma',
 'MI',
 '1 6 1 1 1* - 1 100.00 0 0 0 0',
 '152',
 'Khaleel Ahmed',
 'CSK',
 '1 14 2 2 1* - 2 50.00 0 0 0 0',
 '153',
 'Mohit Sharma',
 'DC',
 '1 8 2 1 1* 1.00 3 33.33 0 0 0 0',
 '154',
 'Donovan Ferreira',
 'DC',
 '1 1 1 0 1 1.00 3 33.33 0 0 0 0',
 '155',
 'Digvesh Singh',
 'LSG',
 '1 13 2 1 1 1.00 3 33.33 0 0 0 0',
 '156',
 'Manoj Bhandage',
 'RCB',
 '1 1 1 0 1 1.00 4 25.00 0 0 0 0']

## reshape the dataset

In [29]:
import numpy as np
player=np.array(player)

In [30]:
player

array(['1', 'Sai Sudharsan', 'GT',
       '759 15 15 1 108* 54.21 486 156.17 1 6 88 21', '2',
       'Surya Kumar Yadav', 'MI',
       '717 16 16 5 73* 65.18 427 167.91 0 5 69 38', '3', 'Virat Kohli',
       'RCB', '657 15 15 3 73* 54.75 454 144.71 0 8 66 19', '4',
       'Shubman Gill', 'GT', '650 15 15 2 93* 50.00 417 155.87 0 6 62 24',
       '5', 'Mitchell Marsh', 'LSG',
       '627 13 13 0 117 48.23 383 163.70 1 6 56 37', '6', 'Shreyas Iyer',
       'PBKS', '604 17 17 5 97* 50.33 345 175.07 0 6 43 39', '7',
       'Yashasvi Jaiswal', 'RR',
       '559 14 14 1 75 43.00 350 159.71 0 6 60 28', '8',
       'Prabhsimran Singh', 'PBKS',
       '549 17 17 0 91 32.29 342 160.52 0 4 56 30', '9', 'K L Rahul',
       'DC', '539 13 13 3 112* 53.90 360 149.72 1 3 52 21', '10',
       'Jos Buttler', 'GT', '538 14 13 4 97* 59.78 330 163.03 0 5 52 24',
       '11', 'Nicholas Pooran', 'LSG',
       '524 14 14 2 87* 43.67 267 196.25 0 5 45 40', '12',
       'Heinrich Klaasen', 'SRH',
       '487 13 13 2 105* 44.27 282 172.69 1 1 42 25', '13',
       'Priyansh Arya', 'PBKS',
       '475 17 17 0 103 27.94 265 179.24 1 2 55 25', '14',
       'Aiden Markram', 'LSG',
       '445 13 13 0 66 34.23 299 148.82 0 5 38 22', '15',
       'Abhishek Sharma', 'SRH',
       '439 14 13 0 141 33.77 227 193.39 1 2 46 28', '16', 'Rohit Sharma',
       'MI', '418 15 15 1 81 29.86 280 149.28 0 4 41 22', '17',
       'Phil Salt', 'RCB', '403 13 13 1 65 33.58 229 175.98 0 4 48 22',
       '18', 'Riyan Parag', 'RR',
       '393 14 14 2 95 32.75 236 166.52 0 1 27 27', '19',
       'Ajinkya Rahane', 'KKR',
       '390 13 12 1 61 35.45 264 147.72 0 3 36 20', '20',
       'Ryan Rickelton', 'MI',
       '388 14 14 1 62* 29.85 257 150.97 0 3 47 17', '21', 'Travis Head',
       'SRH', '374 13 12 0 76 31.17 230 162.60 0 3 50 15', '22',
       'Nehal Wadhera', 'PBKS',
       '369 16 15 3 70 30.75 253 145.84 0 2 28 21', '23', 'Shivam Dube',
       'CSK', '357 14 14 3 50 32.45 270 132.22 0 1 22 21', '24',
       'Ishan Kishan', 'SRH',
       '354 14 13 3 106* 35.40 232 152.58 1 1 33 15', '25',
       'Shashank Singh', 'PBKS',
       '350 17 14 7 61* 50.00 228 153.50 0 3 23 18', '26',
       'N Tilak Varma', 'MI', '343 16 13 2 59 31.18 248 138.30 0 2 23 16',
       '27', 'Dhruv Jurel', 'RR',
       '333 14 13 4 70 37.00 213 156.33 0 2 22 22', '28', 'Ayush Badoni',
       'LSG', '329 14 11 1 74 32.90 222 148.19 0 2 27 14', '29',
       'Rajat Patidar', 'RCB',
       '312 15 14 1 64 24.00 217 143.77 0 2 25 14', '30', 'Abishek Porel',
       'DC', '301 13 13 1 51 25.08 205 146.82 0 1 28 12', '31',
       'Ravindra Jadeja', 'CSK',
       '301 14 14 5 77* 33.44 222 135.58 0 2 25 10', '32',
       'Tristan Stubbs', 'DC',
       '300 14 13 7 41* 50.00 199 150.75 0 0 25 11', '33',
       'Angkrish Raghuvanshi', 'KKR',
       '300 12 11 2 50 33.33 215 139.53 0 1 30 8', '34',
       'Sherfane Rutherford', 'GT',
       '291 13 11 2 46 32.33 185 157.29 0 0 22 18', '35', 'Sanju Samson',
       'RR', '285 9 9 1 66 35.63 203 140.39 0 1 27 13', '36',
       'Josh Inglis', 'PBKS', '278 11 11 2 73 30.89 171 162.57 0 1 26 16',
       '37', 'Rishabh Pant', 'LSG',
       '269 14 13 2 118* 24.45 202 133.16 1 1 23 16', '38', 'Axar Patel',
       'DC', '263 12 11 1 43 26.30 167 157.48 0 0 23 15', '39',
       'Jitesh Sharma', 'RCB',
       '261 15 11 4 85* 37.29 148 176.35 0 1 24 17', '40',
       'Vaibhav Suryavanshi', 'RR',
       '252 7 7 0 101 36.00 122 206.55 1 1 18 24', '41', 'Naman Dhir',
       'MI', '252 16 12 4 46 31.50 138 182.60 0 0 24 13', '42',
       'Devdutt Padikkal', 'RCB',
       '247 10 10 1 61 27.44 164 150.60 0 2 21 14', '43', 'Sunil Narine',
       'KKR', '246 12 12 1 44 22.36 144 170.83 0 0 25 19', '44',
       'Ayush Mhatre', 'CSK', '240 7 7 0 94 34.29 127 188.97 0 1 31 11',
       '45', 'Shimron Hetmyer', 'RR',
       '239 14 13 2 52 21.73 164 145.73 0 1 17 11', '46', 'Aniket Verma',
       'SRH', '236 14 12 3 74 26.22 142 166.19 0 1 12 20', '47',
       'Will Jacks', 'MI', '233 13 11 1 53 23.30 172 135.46 0 1 22 11',
       '48', 'Dewald Brevis', 'CSK',
       '225 6 6 0 57 37.50 125 180.00 0 2 13 17', '49', 'Hardik Pandya',
       'MI', '224 15 12 3 48* 24.89 137 163.50 0 0 18 12', '50',
       'Nitish Rana', 'RR', '217 11 11 1 81 21.70 134 161.94 0 2 27 9',
       '51', 'Rinku Singh', 'KKR',
       '206 13 11 4 38* 29.43 134 153.73 0 0 20 10', '52',
       'Ashutosh Sharma', 'DC',
       '204 13 9 2 66* 29.14 127 160.62 0 1 14 13', '53',
       'Faf Du Plessis', 'DC', '202 9 9 0 62 22.44 163 123.92 0 2 18 8',
       '54', 'Karun Nair', 'DC',
       '198 8 8 0 89 24.75 115 172.17 0 1 24 10', '55', 'MS Dhoni', 'CSK',
       '196 14 13 5 30* 24.50 145 135.17 0 0 12 12', '56',
       'Rachin Ravindra', 'CSK',
       '191 8 8 1 65* 27.29 149 128.18 0 1 18 4', '57', 'Tim David',
       'RCB', '187 12 9 6 50* 62.33 101 185.14 0 1 16 14', '58',
       'Nitish Kumar Reddy', 'SRH',
       '182 13 11 3 32 22.75 153 118.95 0 0 16 4', '59', 'Shahrukh Khan',
       'GT', '179 15 11 5 57 29.83 100 179.00 0 1 11 13', '60',
       'Andre Russell', 'KKR',
       '167 13 10 1 57* 18.56 102 163.72 0 1 16 14', '61', 'Abdul Samad',
       'LSG', '164 13 12 4 45 20.50 93 176.34 0 0 8 14', '62',
       'Marcus Stoinis', 'PBKS',
       '160 13 11 5 44* 26.67 86 186.04 0 0 8 15', '63', 'Devon Conway',
       'CSK', '156 6 6 0 69 26.00 119 131.09 0 2 17 4', '64',
       'David Miller', 'LSG', '153 11 11 6 27* 30.60 120 127.50 0 0 13 4',
       '65', 'Quinton De Kock', 'KKR',
       '152 8 8 1 97* 21.71 117 129.91 0 1 9 11', '66', 'Vipraj Nigam',
       'DC', '142 14 8 1 39 20.29 79 179.74 0 0 15 8', '67',
       'Venkatesh Iyer', 'KKR', '142 11 7 0 60 20.29 102 139.21 0 1 15 4',
       '68', 'Washington Sundar', 'GT',
       '133 6 5 0 49 26.60 80 166.25 0 0 10 7', '69', 'Ruturaj Gaikwad',
       'CSK', '122 5 5 0 63 24.40 81 150.61 0 2 14 4', '70',
       'Sameer Rizvi', 'DC', '121 5 4 1 58* 40.33 79 153.16 0 1 11 7',
       '71', 'Vijay Shankar', 'CSK',
       '118 6 5 2 69* 39.33 91 129.67 0 1 8 3', '72', 'Sam Curran', 'CSK',
       '114 5 5 0 88 22.80 84 135.71 0 1 11 4', '73', 'Liam Livingstone',
       'RCB', '112 10 8 1 54 16.00 84 133.33 0 1 4 9', '74',
       'Krunal Pandya', 'RCB', '109 15 7 1 73* 18.17 86 126.74 0 1 9 4',
       '75', 'Shubham Dubey', 'RR',
       '106 9 8 4 34* 26.50 66 160.60 0 0 6 8', '76', 'Rahul Tewatia',
       'GT', '99 15 12 4 24* 12.38 59 167.79 0 0 6 7', '77',
       'Pat Cummins', 'SRH', '97 14 9 5 22* 24.25 58 167.24 0 0 6 7',
       '78', 'Mayank Agarwal', 'RCB',
       '95 4 4 1 41* 31.67 64 148.43 0 0 10 2', '79', 'Manish Pandey',
       'KKR', '92 3 3 1 37 46.00 65 141.53 0 0 5 5', '80',
       'Kamindu Mendis', 'SRH', '92 5 5 2 32* 30.67 69 133.33 0 0 7 2',
       '81', 'Jonny Bairstow', 'MI',
       '85 2 2 0 47 42.50 46 184.78 0 0 7 5', '82', 'Marco Jansen',
       'PBKS', '75 14 8 4 34* 18.75 63 119.04 0 0 3 4', '83',
       'Rahmanullah Gurbaz', 'KKR',
       '74 5 5 1 35 18.50 53 139.62 0 0 10 3', '84', 'Shaik Rasheed',
       'CSK', '71 5 5 0 27 14.20 63 112.69 0 0 9 2', '85',
       'Romario Shepherd', 'RCB', '70 8 3 1 53* 35.00 24 291.66 0 1 5 7',
       '86', 'Urvil Patel', 'CSK', '68 3 3 0 37 22.67 32 212.50 0 0 5 6',
       '87', 'Jacob Bethell', 'RCB',
       '67 2 2 0 55 33.50 39 171.79 0 1 9 3', '88', 'Jofra Archer', 'RR',
       '63 12 7 1 30 10.50 50 126.00 0 0 3 4', '89', 'Abhinav Manohar',
       'SRH', '61 8 5 0 43 12.20 61 100.00 0 0 2 4', '90',
       'Azmatullah Omarzai', 'PBKS',
       '57 9 5 1 21* 14.25 41 139.02 0 0 6 3', '91', 'Harshit Rana',
       'KKR', '57 13 7 3 34 14.25 53 107.54 0 0 5 3', '92',
       'Jake Fraser - McGurk', 'DC', '55 6 6 0 38 9.17 52 105.76 0 0 7 2',
       '93', 'Rahul Tripathi', 'CSK',
       '55 5 5 0 23 11.00 57 96.49 0 0 6 1', '94', 'Glenn Maxwell',
       'PBKS', '48 7 6 0 30 8.00 49 97.95 0 0 5 1', '95', 'Corbin Bosch',
       'MI', '47 2 2 0 27 23.50 32 146.87 0 0 3 3', '96',
       'Ramandeep Singh', 'KKR', '47 11 7 2 22 9.40 35 134.28 0 0 1 4',
       '97', 'Rashid Khan', 'GT', '40 15 8 3 12 8.00 28 142.85 0 0 2 3',
       '98', 'Mitchell Santner', 'MI',
       '40 13 8 6 18* 20.00 33 121.21 0 0 2 3', '99', 'Deepak Chahar',
       'MI', '37 14 4 3 28* 37.00 25 148.00 0 0 3 2', '100',
       'Ravichandran Ashwin', 'CSK', '33 9 4 0 13 8.25 30 110.00 0 0 3 1',
       '101', 'Deepak Hooda', 'CSK', '31 7 5 0 22 6.20 41 75.60 0 0 2 1',
       '102', 'Mohd Arshad Khan', 'GT',
       '23 9 5 3 20 11.50 19 121.05 0 0 0 3', '103', 'Sediqullah Atal',
       'DC', '22 1 1 0 22 22.00 16 137.50 0 0 0 2', '104', 'Avesh Khan',
       'LSG', '21 13 4 3 19* 21.00 12 175.00 0 0 3 1', '105',
       'Harshal Patel', 'SRH', '21 13 4 2 12* 10.50 26 80.76 0 0 0 0',
       '106', 'Kusal Mendis', 'GT', '20 1 1 0 20 20.00 10 200.00 0 0 1 2',
       '107', 'Shardul Thakur', 'LSG',
       '18 10 5 2 6 6.00 12 150.00 0 0 3 0', '108', 'Kuldeep Yadav', 'DC',
       '18 14 5 2 7 6.00 16 112.50 0 0 2 0', '109', 'Gerald Coetzee',
       'GT', '17 4 2 0 12 8.50 11 154.54 0 0 2 1', '110', 'Jamie Overton',
       'CSK', '15 3 2 2 11* - 7 214.28 0 0 1 1', '111', 'Anshul Kamboj',
       'CSK', '14 8 5 3 5* 7.00 12 116.66 0 0 2 0', '112',
       'Matthew Breetzke', 'LSG', '14 1 1 0 14 14.00 12 116.66 0 0 1 1',
       '113', 'Bhuvneshwar Kumar', 'RCB',
       '14 14 6 3 8 4.67 25 56.00 0 0 1 0', '114', 'Atharva Taide', 'SRH',
       '13 1 1 0 13 13.00 9 144.44 0 0 3 0', '115', 'Ravi Bishnoi', 'LSG',
       '13 11 3 1 13 6.50 16 81.25 0 0 0 2', '116', 'Harpreet Brar',
       'PBKS', '11 8 2 1 7* 11.00 13 84.61 0 0 0 1', '117',
       'Xavier Bartlett', 'PBKS', '11 4 1 0 11 11.00 15 73.33 0 0 1 0',
       '118', 'Mohammad Shami', 'SRH',
       '10 9 4 3 6* 10.00 10 100.00 0 0 1 0', '119',
       'Dushmantha Chameera', 'DC', '10 6 3 3 8* - 14 71.42 0 0 0 0',
       '120', 'Maheesh Theekshana', 'RR',
       '10 11 4 2 5 5.00 27 37.03 0 0 0 0', '121', 'Kagiso Rabada', 'GT',
       '9 4 2 1 7* 9.00 8 112.50 0 0 0 1', '122', 'Shahbaz Ahmed', 'LSG',
       '9 3 1 0 9 9.00 8 112.50 0 0 1 0', '123', 'Wiaan Mulder', 'SRH',
       '9 1 1 0 9 9.00 11 81.81 0 0 1 0', '124', 'Wanindu Hasaranga',
       'RR', '9 11 5 0 4 1.80 15 60.00 0 0 0 0', '125', 'Kwena Maphaka',
       'RR', '8 2 1 1 8* - 2 400.00 0 0 2 0', '126', 'Raj Angad Bawa',
       'MI', '8 3 1 1 8* - 4 200.00 0 0 0 0', '127', 'Tushar Deshpande',
       'RR', '7 10 4 3 3 7.00 8 87.50 0 0 0 0', '128', 'Suryansh Shedge',
       'PBKS', '7 5 3 0 4 2.33 11 63.63 0 0 0 0', '129', 'Noor Ahmad',
       'CSK', '7 14 6 2 2* 1.75 17 41.17 0 0 0 0', '130', 'Akash Deep',
       'LSG', '6 6 2 1 6* 6.00 2 300.00 0 0 0 1', '131', 'Sandeep Sharma',
       'RR', '6 10 1 1 6* - 5 120.00 0 0 0 0', '132', 'Mitchell Starc',
       'DC', '6 11 6 4 2* 3.00 10 60.00 0 0 0 0', '133', 'Robin Minz',
       'MI', '6 2 2 0 3 3.00 15 40.00 0 0 0 0', '134', 'Rovman Powell',
       'KKR', '5 2 1 0 5 5.00 5 100.00 0 0 1 0', '135', 'Sai Kishore',
       'GT', '5 15 3 0 3 1.67 10 50.00 0 0 0 0', '136', 'Prince Yadav',
       'LSG', '5 6 2 2 4* - 10 50.00 0 0 0 0', '137', 'Moeen Ali', 'KKR',
       '5 6 2 0 5 2.50 14 35.71 0 0 0 0', '138', 'Lockie Ferguson',
       'PBKS', '4 4 1 1 4* - 1 400.00 0 0 1 0', '139', 'Yash Dayal',
       'RCB', '4 15 3 1 3 2.00 8 50.00 0 0 0 0', '140', 'Akash Madhwal',
       'RR', '4 4 1 1 4* - 9 44.44 0 0 0 0', '141', 'Madhav Tiwari', 'DC',
       '3 1 1 0 3 3.00 4 75.00 0 0 0 0', '142', 'Mohammed Siraj', 'GT',
       '3 15 1 1 3* - 4 75.00 0 0 0 0', '143', 'Kumar Kartikeya Singh',
       'RR', '3 4 2 0 2 1.50 5 60.00 0 0 0 0', '144', 'Simarjeet Singh',
       'SRH', '3 4 3 1 3* 1.50 7 42.85 0 0 0 0', '145',
       'Fazalhaq Farooqi', 'RR', '2 5 1 1 2* - 2 100.00 0 0 0 0', '146',
       'Trent Boult', 'MI', '2 16 2 1 1* 2.00 3 66.66 0 0 0 0', '147',
       'Spencer Johnson', 'KKR', '2 4 2 2 1* - 4 50.00 0 0 0 0', '148',
       'Arshdeep Singh', 'PBKS', '2 17 2 1 1* 2.00 6 33.33 0 0 0 0',
       '149', 'Varun Chakaravarthy', 'KKR',
       '1 13 1 1 1* - 1 100.00 0 0 0 0', '150',
       'V Satyanarayana Penmetsa', 'MI', '1 2 1 1 1* - 1 100.00 0 0 0 0',
       '151', 'Karn Sharma', 'MI', '1 6 1 1 1* - 1 100.00 0 0 0 0', '152',
       'Khaleel Ahmed', 'CSK', '1 14 2 2 1* - 2 50.00 0 0 0 0', '153',
       'Mohit Sharma', 'DC', '1 8 2 1 1* 1.00 3 33.33 0 0 0 0', '154',
       'Donovan Ferreira', 'DC', '1 1 1 0 1 1.00 3 33.33 0 0 0 0', '155',
       'Digvesh Singh', 'LSG', '1 13 2 1 1 1.00 3 33.33 0 0 0 0', '156',
       'Manoj Bhandage', 'RCB', '1 1 1 0 1 1.00 4 25.00 0 0 0 0'],
      dtype='<U43')

In [31]:
player.size

624

In [32]:
624/4

156.0

In [37]:
player.ndim

1

In [38]:
player.shape

(624,)

In [51]:
player=player.reshape((156,4))
player

array([['1', 'Sai Sudharsan', 'GT',
        '759 15 15 1 108* 54.21 486 156.17 1 6 88 21'],
       ['2', 'Surya Kumar Yadav', 'MI',
        '717 16 16 5 73* 65.18 427 167.91 0 5 69 38'],
       ['3', 'Virat Kohli', 'RCB',
        '657 15 15 3 73* 54.75 454 144.71 0 8 66 19'],
       ['4', 'Shubman Gill', 'GT',
        '650 15 15 2 93* 50.00 417 155.87 0 6 62 24'],
       ['5', 'Mitchell Marsh', 'LSG',
        '627 13 13 0 117 48.23 383 163.70 1 6 56 37'],
       ['6', 'Shreyas Iyer', 'PBKS',
        '604 17 17 5 97* 50.33 345 175.07 0 6 43 39'],
       ['7', 'Yashasvi Jaiswal', 'RR',
        '559 14 14 1 75 43.00 350 159.71 0 6 60 28'],
       ['8', 'Prabhsimran Singh', 'PBKS',
        '549 17 17 0 91 32.29 342 160.52 0 4 56 30'],
       ['9', 'K L Rahul', 'DC',
        '539 13 13 3 112* 53.90 360 149.72 1 3 52 21'],
       ['10', 'Jos Buttler', 'GT',
        '538 14 13 4 97* 59.78 330 163.03 0 5 52 24'],
       ['11', 'Nicholas Pooran', 'LSG',
        '524 14 14 2 87* 43.67 267 196.25 0 5 45 40'],
       ['12', 'Heinrich Klaasen', 'SRH',
        '487 13 13 2 105* 44.27 282 172.69 1 1 42 25'],
       ['13', 'Priyansh Arya', 'PBKS',
        '475 17 17 0 103 27.94 265 179.24 1 2 55 25'],
       ['14', 'Aiden Markram', 'LSG',
        '445 13 13 0 66 34.23 299 148.82 0 5 38 22'],
       ['15', 'Abhishek Sharma', 'SRH',
        '439 14 13 0 141 33.77 227 193.39 1 2 46 28'],
       ['16', 'Rohit Sharma', 'MI',
        '418 15 15 1 81 29.86 280 149.28 0 4 41 22'],
       ['17', 'Phil Salt', 'RCB',
        '403 13 13 1 65 33.58 229 175.98 0 4 48 22'],
       ['18', 'Riyan Parag', 'RR',
        '393 14 14 2 95 32.75 236 166.52 0 1 27 27'],
       ['19', 'Ajinkya Rahane', 'KKR',
        '390 13 12 1 61 35.45 264 147.72 0 3 36 20'],
       ['20', 'Ryan Rickelton', 'MI',
        '388 14 14 1 62* 29.85 257 150.97 0 3 47 17'],
       ['21', 'Travis Head', 'SRH',
        '374 13 12 0 76 31.17 230 162.60 0 3 50 15'],
       ['22', 'Nehal Wadhera', 'PBKS',
        '369 16 15 3 70 30.75 253 145.84 0 2 28 21'],
       ['23', 'Shivam Dube', 'CSK',
        '357 14 14 3 50 32.45 270 132.22 0 1 22 21'],
       ['24', 'Ishan Kishan', 'SRH',
        '354 14 13 3 106* 35.40 232 152.58 1 1 33 15'],
       ['25', 'Shashank Singh', 'PBKS',
        '350 17 14 7 61* 50.00 228 153.50 0 3 23 18'],
       ['26', 'N Tilak Varma', 'MI',
        '343 16 13 2 59 31.18 248 138.30 0 2 23 16'],
       ['27', 'Dhruv Jurel', 'RR',
        '333 14 13 4 70 37.00 213 156.33 0 2 22 22'],
       ['28', 'Ayush Badoni', 'LSG',
        '329 14 11 1 74 32.90 222 148.19 0 2 27 14'],
       ['29', 'Rajat Patidar', 'RCB',
        '312 15 14 1 64 24.00 217 143.77 0 2 25 14'],
       ['30', 'Abishek Porel', 'DC',
        '301 13 13 1 51 25.08 205 146.82 0 1 28 12'],
       ['31', 'Ravindra Jadeja', 'CSK',
        '301 14 14 5 77* 33.44 222 135.58 0 2 25 10'],
       ['32', 'Tristan Stubbs', 'DC',
        '300 14 13 7 41* 50.00 199 150.75 0 0 25 11'],
       ['33', 'Angkrish Raghuvanshi', 'KKR',
        '300 12 11 2 50 33.33 215 139.53 0 1 30 8'],
       ['34', 'Sherfane Rutherford', 'GT',
        '291 13 11 2 46 32.33 185 157.29 0 0 22 18'],
       ['35', 'Sanju Samson', 'RR',
        '285 9 9 1 66 35.63 203 140.39 0 1 27 13'],
       ['36', 'Josh Inglis', 'PBKS',
        '278 11 11 2 73 30.89 171 162.57 0 1 26 16'],
       ['37', 'Rishabh Pant', 'LSG',
        '269 14 13 2 118* 24.45 202 133.16 1 1 23 16'],
       ['38', 'Axar Patel', 'DC',
        '263 12 11 1 43 26.30 167 157.48 0 0 23 15'],
       ['39', 'Jitesh Sharma', 'RCB',
        '261 15 11 4 85* 37.29 148 176.35 0 1 24 17'],
       ['40', 'Vaibhav Suryavanshi', 'RR',
        '252 7 7 0 101 36.00 122 206.55 1 1 18 24'],
       ['41', 'Naman Dhir', 'MI',
        '252 16 12 4 46 31.50 138 182.60 0 0 24 13'],
       ['42', 'Devdutt Padikkal', 'RCB',
        '247 10 10 1 61 27.44 164 150.60 0 2 21 14'],
       ['43', 'Sunil Narine', 'KKR',
        '246 12 12 1 44 22.36 144 170.83 0 0 25 19'],
       ['44', 'Ayush Mhatre', 'CSK',
        '240 7 7 0 94 34.29 127 188.97 0 1 31 11'],
       ['45', 'Shimron Hetmyer', 'RR',
        '239 14 13 2 52 21.73 164 145.73 0 1 17 11'],
       ['46', 'Aniket Verma', 'SRH',
        '236 14 12 3 74 26.22 142 166.19 0 1 12 20'],
       ['47', 'Will Jacks', 'MI',
        '233 13 11 1 53 23.30 172 135.46 0 1 22 11'],
       ['48', 'Dewald Brevis', 'CSK',
        '225 6 6 0 57 37.50 125 180.00 0 2 13 17'],
       ['49', 'Hardik Pandya', 'MI',
        '224 15 12 3 48* 24.89 137 163.50 0 0 18 12'],
       ['50', 'Nitish Rana', 'RR',
        '217 11 11 1 81 21.70 134 161.94 0 2 27 9'],
       ['51', 'Rinku Singh', 'KKR',
        '206 13 11 4 38* 29.43 134 153.73 0 0 20 10'],
       ['52', 'Ashutosh Sharma', 'DC',
        '204 13 9 2 66* 29.14 127 160.62 0 1 14 13'],
       ['53', 'Faf Du Plessis', 'DC',
        '202 9 9 0 62 22.44 163 123.92 0 2 18 8'],
       ['54', 'Karun Nair', 'DC',
        '198 8 8 0 89 24.75 115 172.17 0 1 24 10'],
       ['55', 'MS Dhoni', 'CSK',
        '196 14 13 5 30* 24.50 145 135.17 0 0 12 12'],
       ['56', 'Rachin Ravindra', 'CSK',
        '191 8 8 1 65* 27.29 149 128.18 0 1 18 4'],
       ['57', 'Tim David', 'RCB',
        '187 12 9 6 50* 62.33 101 185.14 0 1 16 14'],
       ['58', 'Nitish Kumar Reddy', 'SRH',
        '182 13 11 3 32 22.75 153 118.95 0 0 16 4'],
       ['59', 'Shahrukh Khan', 'GT',
        '179 15 11 5 57 29.83 100 179.00 0 1 11 13'],
       ['60', 'Andre Russell', 'KKR',
        '167 13 10 1 57* 18.56 102 163.72 0 1 16 14'],
       ['61', 'Abdul Samad', 'LSG',
        '164 13 12 4 45 20.50 93 176.34 0 0 8 14'],
       ['62', 'Marcus Stoinis', 'PBKS',
        '160 13 11 5 44* 26.67 86 186.04 0 0 8 15'],
       ['63', 'Devon Conway', 'CSK',
        '156 6 6 0 69 26.00 119 131.09 0 2 17 4'],
       ['64', 'David Miller', 'LSG',
        '153 11 11 6 27* 30.60 120 127.50 0 0 13 4'],
       ['65', 'Quinton De Kock', 'KKR',
        '152 8 8 1 97* 21.71 117 129.91 0 1 9 11'],
       ['66', 'Vipraj Nigam', 'DC',
        '142 14 8 1 39 20.29 79 179.74 0 0 15 8'],
       ['67', 'Venkatesh Iyer', 'KKR',
        '142 11 7 0 60 20.29 102 139.21 0 1 15 4'],
       ['68', 'Washington Sundar', 'GT',
        '133 6 5 0 49 26.60 80 166.25 0 0 10 7'],
       ['69', 'Ruturaj Gaikwad', 'CSK',
        '122 5 5 0 63 24.40 81 150.61 0 2 14 4'],
       ['70', 'Sameer Rizvi', 'DC',
        '121 5 4 1 58* 40.33 79 153.16 0 1 11 7'],
       ['71', 'Vijay Shankar', 'CSK',
        '118 6 5 2 69* 39.33 91 129.67 0 1 8 3'],
       ['72', 'Sam Curran', 'CSK',
        '114 5 5 0 88 22.80 84 135.71 0 1 11 4'],
       ['73', 'Liam Livingstone', 'RCB',
        '112 10 8 1 54 16.00 84 133.33 0 1 4 9'],
       ['74', 'Krunal Pandya', 'RCB',
        '109 15 7 1 73* 18.17 86 126.74 0 1 9 4'],
       ['75', 'Shubham Dubey', 'RR',
        '106 9 8 4 34* 26.50 66 160.60 0 0 6 8'],
       ['76', 'Rahul Tewatia', 'GT',
        '99 15 12 4 24* 12.38 59 167.79 0 0 6 7'],
       ['77', 'Pat Cummins', 'SRH',
        '97 14 9 5 22* 24.25 58 167.24 0 0 6 7'],
       ['78', 'Mayank Agarwal', 'RCB',
        '95 4 4 1 41* 31.67 64 148.43 0 0 10 2'],
       ['79', 'Manish Pandey', 'KKR',
        '92 3 3 1 37 46.00 65 141.53 0 0 5 5'],
       ['80', 'Kamindu Mendis', 'SRH',
        '92 5 5 2 32* 30.67 69 133.33 0 0 7 2'],
       ['81', 'Jonny Bairstow', 'MI',
        '85 2 2 0 47 42.50 46 184.78 0 0 7 5'],
       ['82', 'Marco Jansen', 'PBKS',
        '75 14 8 4 34* 18.75 63 119.04 0 0 3 4'],
       ['83', 'Rahmanullah Gurbaz', 'KKR',
        '74 5 5 1 35 18.50 53 139.62 0 0 10 3'],
       ['84', 'Shaik Rasheed', 'CSK',
        '71 5 5 0 27 14.20 63 112.69 0 0 9 2'],
       ['85', 'Romario Shepherd', 'RCB',
        '70 8 3 1 53* 35.00 24 291.66 0 1 5 7'],
       ['86', 'Urvil Patel', 'CSK',
        '68 3 3 0 37 22.67 32 212.50 0 0 5 6'],
       ['87', 'Jacob Bethell', 'RCB',
        '67 2 2 0 55 33.50 39 171.79 0 1 9 3'],
       ['88', 'Jofra Archer', 'RR',
        '63 12 7 1 30 10.50 50 126.00 0 0 3 4'],
       ['89', 'Abhinav Manohar', 'SRH',
        '61 8 5 0 43 12.20 61 100.00 0 0 2 4'],
       ['90', 'Azmatullah Omarzai', 'PBKS',
        '57 9 5 1 21* 14.25 41 139.02 0 0 6 3'],
       ['91', 'Harshit Rana', 'KKR',
        '57 13 7 3 34 14.25 53 107.54 0 0 5 3'],
       ['92', 'Jake Fraser - McGurk', 'DC',
        '55 6 6 0 38 9.17 52 105.76 0 0 7 2'],
       ['93', 'Rahul Tripathi', 'CSK',
        '55 5 5 0 23 11.00 57 96.49 0 0 6 1'],
       ['94', 'Glenn Maxwell', 'PBKS',
        '48 7 6 0 30 8.00 49 97.95 0 0 5 1'],
       ['95', 'Corbin Bosch', 'MI',
        '47 2 2 0 27 23.50 32 146.87 0 0 3 3'],
       ['96', 'Ramandeep Singh', 'KKR',
        '47 11 7 2 22 9.40 35 134.28 0 0 1 4'],
       ['97', 'Rashid Khan', 'GT', '40 15 8 3 12 8.00 28 142.85 0 0 2 3'],
       ['98', 'Mitchell Santner', 'MI',
        '40 13 8 6 18* 20.00 33 121.21 0 0 2 3'],
       ['99', 'Deepak Chahar', 'MI',
        '37 14 4 3 28* 37.00 25 148.00 0 0 3 2'],
       ['100', 'Ravichandran Ashwin', 'CSK',
        '33 9 4 0 13 8.25 30 110.00 0 0 3 1'],
       ['101', 'Deepak Hooda', 'CSK',
        '31 7 5 0 22 6.20 41 75.60 0 0 2 1'],
       ['102', 'Mohd Arshad Khan', 'GT',
        '23 9 5 3 20 11.50 19 121.05 0 0 0 3'],
       ['103', 'Sediqullah Atal', 'DC',
        '22 1 1 0 22 22.00 16 137.50 0 0 0 2'],
       ['104', 'Avesh Khan', 'LSG',
        '21 13 4 3 19* 21.00 12 175.00 0 0 3 1'],
       ['105', 'Harshal Patel', 'SRH',
        '21 13 4 2 12* 10.50 26 80.76 0 0 0 0'],
       ['106', 'Kusal Mendis', 'GT',
        '20 1 1 0 20 20.00 10 200.00 0 0 1 2'],
       ['107', 'Shardul Thakur', 'LSG',
        '18 10 5 2 6 6.00 12 150.00 0 0 3 0'],
       ['108', 'Kuldeep Yadav', 'DC',
        '18 14 5 2 7 6.00 16 112.50 0 0 2 0'],
       ['109', 'Gerald Coetzee', 'GT',
        '17 4 2 0 12 8.50 11 154.54 0 0 2 1'],
       ['110', 'Jamie Overton', 'CSK', '15 3 2 2 11* - 7 214.28 0 0 1 1'],
       ['111', 'Anshul Kamboj', 'CSK',
        '14 8 5 3 5* 7.00 12 116.66 0 0 2 0'],
       ['112', 'Matthew Breetzke', 'LSG',
        '14 1 1 0 14 14.00 12 116.66 0 0 1 1'],
       ['113', 'Bhuvneshwar Kumar', 'RCB',
        '14 14 6 3 8 4.67 25 56.00 0 0 1 0'],
       ['114', 'Atharva Taide', 'SRH',
        '13 1 1 0 13 13.00 9 144.44 0 0 3 0'],
       ['115', 'Ravi Bishnoi', 'LSG',
        '13 11 3 1 13 6.50 16 81.25 0 0 0 2'],
       ['116', 'Harpreet Brar', 'PBKS',
        '11 8 2 1 7* 11.00 13 84.61 0 0 0 1'],
       ['117', 'Xavier Bartlett', 'PBKS',
        '11 4 1 0 11 11.00 15 73.33 0 0 1 0'],
       ['118', 'Mohammad Shami', 'SRH',
        '10 9 4 3 6* 10.00 10 100.00 0 0 1 0'],
       ['119', 'Dushmantha Chameera', 'DC',
        '10 6 3 3 8* - 14 71.42 0 0 0 0'],
       ['120', 'Maheesh Theekshana', 'RR',
        '10 11 4 2 5 5.00 27 37.03 0 0 0 0'],
       ['121', 'Kagiso Rabada', 'GT', '9 4 2 1 7* 9.00 8 112.50 0 0 0 1'],
       ['122', 'Shahbaz Ahmed', 'LSG', '9 3 1 0 9 9.00 8 112.50 0 0 1 0'],
       ['123', 'Wiaan Mulder', 'SRH', '9 1 1 0 9 9.00 11 81.81 0 0 1 0'],
       ['124', 'Wanindu Hasaranga', 'RR',
        '9 11 5 0 4 1.80 15 60.00 0 0 0 0'],
       ['125', 'Kwena Maphaka', 'RR', '8 2 1 1 8* - 2 400.00 0 0 2 0'],
       ['126', 'Raj Angad Bawa', 'MI', '8 3 1 1 8* - 4 200.00 0 0 0 0'],
       ['127', 'Tushar Deshpande', 'RR',
        '7 10 4 3 3 7.00 8 87.50 0 0 0 0'],
       ['128', 'Suryansh Shedge', 'PBKS',
        '7 5 3 0 4 2.33 11 63.63 0 0 0 0'],
       ['129', 'Noor Ahmad', 'CSK', '7 14 6 2 2* 1.75 17 41.17 0 0 0 0'],
       ['130', 'Akash Deep', 'LSG', '6 6 2 1 6* 6.00 2 300.00 0 0 0 1'],
       ['131', 'Sandeep Sharma', 'RR', '6 10 1 1 6* - 5 120.00 0 0 0 0'],
       ['132', 'Mitchell Starc', 'DC',
        '6 11 6 4 2* 3.00 10 60.00 0 0 0 0'],
       ['133', 'Robin Minz', 'MI', '6 2 2 0 3 3.00 15 40.00 0 0 0 0'],
       ['134', 'Rovman Powell', 'KKR', '5 2 1 0 5 5.00 5 100.00 0 0 1 0'],
       ['135', 'Sai Kishore', 'GT', '5 15 3 0 3 1.67 10 50.00 0 0 0 0'],
       ['136', 'Prince Yadav', 'LSG', '5 6 2 2 4* - 10 50.00 0 0 0 0'],
       ['137', 'Moeen Ali', 'KKR', '5 6 2 0 5 2.50 14 35.71 0 0 0 0'],
       ['138', 'Lockie Ferguson', 'PBKS',
        '4 4 1 1 4* - 1 400.00 0 0 1 0'],
       ['139', 'Yash Dayal', 'RCB', '4 15 3 1 3 2.00 8 50.00 0 0 0 0'],
       ['140', 'Akash Madhwal', 'RR', '4 4 1 1 4* - 9 44.44 0 0 0 0'],
       ['141', 'Madhav Tiwari', 'DC', '3 1 1 0 3 3.00 4 75.00 0 0 0 0'],
       ['142', 'Mohammed Siraj', 'GT', '3 15 1 1 3* - 4 75.00 0 0 0 0'],
       ['143', 'Kumar Kartikeya Singh', 'RR',
        '3 4 2 0 2 1.50 5 60.00 0 0 0 0'],
       ['144', 'Simarjeet Singh', 'SRH',
        '3 4 3 1 3* 1.50 7 42.85 0 0 0 0'],
       ['145', 'Fazalhaq Farooqi', 'RR', '2 5 1 1 2* - 2 100.00 0 0 0 0'],
       ['146', 'Trent Boult', 'MI', '2 16 2 1 1* 2.00 3 66.66 0 0 0 0'],
       ['147', 'Spencer Johnson', 'KKR', '2 4 2 2 1* - 4 50.00 0 0 0 0'],
       ['148', 'Arshdeep Singh', 'PBKS',
        '2 17 2 1 1* 2.00 6 33.33 0 0 0 0'],
       ['149', 'Varun Chakaravarthy', 'KKR',
        '1 13 1 1 1* - 1 100.00 0 0 0 0'],
       ['150', 'V Satyanarayana Penmetsa', 'MI',
        '1 2 1 1 1* - 1 100.00 0 0 0 0'],
       ['151', 'Karn Sharma', 'MI', '1 6 1 1 1* - 1 100.00 0 0 0 0'],
       ['152', 'Khaleel Ahmed', 'CSK', '1 14 2 2 1* - 2 50.00 0 0 0 0'],
       ['153', 'Mohit Sharma', 'DC', '1 8 2 1 1* 1.00 3 33.33 0 0 0 0'],
       ['154', 'Donovan Ferreira', 'DC',
        '1 1 1 0 1 1.00 3 33.33 0 0 0 0'],
       ['155', 'Digvesh Singh', 'LSG', '1 13 2 1 1 1.00 3 33.33 0 0 0 0'],
       ['156', 'Manoj Bhandage', 'RCB', '1 1 1 0 1 1.00 4 25.00 0 0 0 0']],
      dtype='<U43')

## conver to Dataframe

In [46]:
import pandas as pd
df=pd.DataFrame(player)

In [47]:
df[3]

0      759 15 15 1 108* 54.21 486 156.17 1 6 88 21
1       717 16 16 5 73* 65.18 427 167.91 0 5 69 38
2       657 15 15 3 73* 54.75 454 144.71 0 8 66 19
3       650 15 15 2 93* 50.00 417 155.87 0 6 62 24
4       627 13 13 0 117 48.23 383 163.70 1 6 56 37
                          ...
151                  1 14 2 2 1* - 2 50.00 0 0 0 0
152                1 8 2 1 1* 1.00 3 33.33 0 0 0 0
153                 1 1 1 0 1 1.00 3 33.33 0 0 0 0
154                1 13 2 1 1 1.00 3 33.33 0 0 0 0
155                 1 1 1 0 1 1.00 4 25.00 0 0 0 0
Name: 3, Length: 156, dtype: object

In [48]:
df[3][0]

'759 15 15 1 108* 54.21 486 156.17 1 6 88 21'

In [52]:
df[3][0].split('/n')

['759 15 15 1 108* 54.21 486 156.17 1 6 88 21']

In [58]:
other_info=df[3].str.split(expand=True) #.str.get[0]
other_info

      0   1   2  3     4      5    6       7  8  9   10  11
0    759  15  15  1  108*  54.21  486  156.17  1  6  88  21
1    717  16  16  5   73*  65.18  427  167.91  0  5  69  38
2    657  15  15  3   73*  54.75  454  144.71  0  8  66  19
3    650  15  15  2   93*  50.00  417  155.87  0  6  62  24
4    627  13  13  0   117  48.23  383  163.70  1  6  56  37
..   ...  ..  .. ..   ...    ...  ...     ... .. ..  ..  ..
151    1  14   2  2    1*      -    2   50.00  0  0   0   0
152    1   8   2  1    1*   1.00    3   33.33  0  0   0   0
153    1   1   1  0     1   1.00    3   33.33  0  0   0   0
154    1  13   2  1     1   1.00    3   33.33  0  0   0   0
155    1   1   1  0     1   1.00    4   25.00  0  0   0   0

[156 rows x 12 columns]

In [60]:
df=df.iloc[:,:-1]
df

       0                  1    2
0      1      Sai Sudharsan   GT
1      2  Surya Kumar Yadav   MI
2      3        Virat Kohli  RCB
3      4       Shubman Gill   GT
4      5     Mitchell Marsh  LSG
..   ...                ...  ...
151  152      Khaleel Ahmed  CSK
152  153       Mohit Sharma   DC
153  154   Donovan Ferreira   DC
154  155      Digvesh Singh  LSG
155  156     Manoj Bhandage  RCB

[156 rows x 3 columns]

## concat the DF

In [63]:
final=pd.concat([df,other_info],axis=1)
final

,0,1,2,0,1,2,3,4,5,6,7,8,9,10,11
0,1,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,2,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,3,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,4,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,5,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,153,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,154,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,155,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,156,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [75]:
len(cols)

14

In [76]:
final.columns

Index([0, 1, 2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64')

In [82]:
cols=cols[:2]+['Team']+cols[2:]
cols

['POS',
 'Player',
 'Team',
 'Team',
 'Runs',
 'Mat',
 'Inns',
 'NO',
 'HS',
 'Avg',
 'BF',
 'SR',
 '100',
 '50',
 '4s',
 '6s']

In [81]:
final.columns=cols
final

,POS,Player,Team,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,2,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,3,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,4,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,5,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,153,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,154,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,155,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,156,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [87]:
def extract_data(data):
    cols=data.split('\n')[0].split()
    player=data.split('\n')[1:]
    player=np.array(player)
    no_of_player=int((player.size)/4)
    player=player.reshape((no_of_player,4))
    df=pd.DataFrame(player)
    other_info=df[3].str.split(expand=True)
    df=df.iloc[:,:-1]
    final=pd.concat([df,other_info],axis=1)
    cols=cols[:2]+['Temp']+cols[2:]
    final.columns=cols
    return final

In [88]:
extract_data(data)

,POS,Player,Temp,Runs,Mat,Inns,NO,HS,Avg,BF,SR,100,50,4s,6s
0,1,Virat Kohli,RCB,741,15,15,3,113*,61.75,479,154.69,1,5,62,38
1,2,Ruturaj Gaikwad,CSK,583,14,14,3,108*,53.00,413,141.16,1,4,58,18
2,3,Riyan Parag,RR,573,16,14,3,84*,52.09,384,149.21,0,4,40,33
3,4,Travis Head,SRH,567,15,15,1,102,40.50,296,191.55,1,4,64,32
4,5,Sanju Samson,RR,531,16,15,4,86,48.27,346,153.46,0,5,48,24
5,6,Sai Sudharsan,GT,527,12,12,1,103,47.91,373,141.28,1,2,48,16
6,7,K L Rahul,LSG,520,14,14,0,82,37.14,382,136.12,0,4,45,19
7,8,Nicholas Pooran,LSG,499,14,14,6,75,62.38,280,178.21,0,3,35,36
8,9,Sunil Narine,KKR,488,15,14,0,109,34.86,270,180.74,1,3,50,33
9,10,Abhishek Sharma,SRH,484,16,16,1,75*,32.27,237,204.21,0,3,36,42
10,11,Heinrich Klaasen,SRH,479,16,15,3,80*,39.92,280,171.07,0,4,19,38
11,12,Rishabh Pant,DC,446,13,13,2,88*,40.55,287,155.40,0,3,36,25
12,13,Faf Du Plessis,RCB,438,15,15,0,64,29.20,271,161.62,0,4,47,21
13,14,Phil Salt,KKR,435,12,12,1,89*,39.55,239,182.00,0,4,50,24
14,15,Yashasvi Jaiswal,RR,435,16,15,1,104*,31.07,279,155.91,1,1,54,16
15,16,Shubman Gill,GT,426,12,12,1,104,38.73,289,147.40,1,2,37,15
16,17,Rohit Sharma,MI,417,14,14,1,105*,32.08,278,150.00,1,1,45,23
17,18,Tilak Varma,MI,416,13,13,3,65,41.60,278,149.64,0,3,35,19
18,19,Shivam Dube,CSK,396,14,14,3,66*,36.00,244,162.29,0,3,28,28
19,20,Rajat Patidar,RCB,395,15,13,0,55,30.38,223,177.13,0,5,21,33

In [89]:
driver=webdriver.Chrome()
import time 
all_data={}

for i in range(2008,2025):
    driver.get(f'https://www.iplt20.com/stats/{i}')
    time.sleep(10)
    data=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/div[4]/div/section/div/div[3]/div[2]/div[2]/div/div[3]/div/div[1]/table/tbody').text
    df=extract_data(data)
    df['Year']=i
    all_data[i]=df
    df.to_csv(f'E:\\Datascience\\dataset\\IPL\\{i}.csv')
    print(f'{i} year data extracted')

2008 year data extracted
2009 year data extracted
2010 year data extracted
2011 year data extracted
2012 year data extracted
2013 year data extracted
2014 year data extracted
2015 year data extracted
2016 year data extracted
2017 year data extracted
2018 year data extracted
2019 year data extracted
2020 year data extracted
2021 year data extracted
2022 year data extracted
2023 year data extracted
2024 year data extracted

In [90]:
driver.quit()